### PR TITLE
Update the interface for declaring Python download preferences

### PR DESCRIPTION
**Pull request by zanieb**
The loose consensus is that "fetch" doesn't have much meaning and that a boolean flag makes more sense from the command line.

1. Adds `--allow-python-downloads` (hidden, default) and `--no-python-downloads` to the CLI to quickly enable or disable downloads
2. Deprecates `--python-fetch` in favor of the options from (1)
3. Removes  `python-fetch` in favor of a `python-downloads` setting
5. Adds a `never` variant to the enum, allowing even explicit installs to be disabled via the configuration file

## Test plan

I tested this with various `pyproject.toml`-level settings and `uv venv --preview --python 3.12.2` and `uv python install 3.12.2` with and without the new CLI flags.

### CODE REVIEW

**Comment by zanieb** [comment]
Notably I did not deprecate the `python-fetch` setting, just removed it. I'm not sure what the pattern is to deprecate a setting yet.

**Comment by zanieb** [comment]
I'm a little uncertain of the "never" value, but I do think it has some utility to require explicit opt-in from the CLI to install versions.

**Comment by zanieb** [comment]
Whoops I checked in my `pyproject.toml` change, and look, it works https://github.com/astral-sh/uv/actions/runs/10310109626/job/28541254932?pr=5936

**Comment by charliermarsh** [comment]
Thanks. Am I right that `--python-downloads` isn't exposed on the command line? So those settings are only available in a configuration file?

I'm wondering it it should be `--download-python` and `--no-download-python` to match settings like `--compile-bytecode`. Are we consistent with that pattern?

**Comment by zanieb** [comment]
I leaned away from `--download-python` because it won't _force_ Python to be downloaded, it just allows it if it would be, e.g. `--python-preference only-system --download-python` would still never download Python.

**Comment by zanieb** [comment]
> Am I right that --python-downloads isn't exposed on the command line? So those settings are only available in a configuration file?

Yes, only a boolean option is available from the command line and the "manual" value is only accessible via the configuration file. I find that a little peculiar, but don't think it'll be problematic in practice.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
