### PR TITLE
Support relative path wheels

### LINKED ISSUE #4355: Support relative path wheel dependencies
Currently, we only support locking relative path for directory and source dist dependencies. We need to also support relative paths for wheels. To implement this, we need to add the install path vs. lock path split to `PathBuiltDist`, just as we do with `PathSourceDist`.

Failing example:

```toml
[project]
name = "project"
version = "0.1.0"
dependencies = [
  "tqdm"
]
requires-python = ">=3.8"

[tool.uv.sources]
tqdm = { path = "./tqdm-4.66.4-py3-none-any.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

The lockfile entry should have the relative path, not the absolute path:

```toml
[[distribution]]
name = "tqdm"
version = "4.66.4"
source = { path = "/home/konsti/projects/uv/debug/dummy/tqdm-4.66.4-py3-none-any.whl" }
dependencies = [
    { name = "colorama", marker = "platform_system == 'Windows'" },
]
wheels = [
    { url = "file:///home/konsti/projects/uv/debug/dummy/tqdm-4.66.4-py3-none-any.whl", hash = "sha256:b75ca56b413b030bc3f00af51fd2c1a1a5eac6a0c1cca83cbb37a5c52abce644" },
]
```

### PR DESCRIPTION
**Pull request by konstin**
Surprisingly, this is a lockfile schema change: We can't store relative paths in urls, so we have to store a `filename` entry instead of the whole url.

Fixes #4355

### CODE REVIEW

**Comment by charliermarsh** [comment]
Why do we drop the hash?

**Comment by konstin** [comment]
If the hash is important, i can add a new `wheels` entry variant. Currently, it's dropped because we can't represent the relative path as the `url` that `wheels` entries use.

**Comment by charliermarsh** [comment]
I think it's worth adding two variants to wheels.

**Comment by konstin** [comment]
We don't drop the hash anymore.

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Thanks, this looks good. It would be nice to remove the duplicated filename but... not critical.

**Comment by charliermarsh** [comment]
Debugging test failure, then will merge.

**Comment by charliermarsh** [comment]
Ok this is an actual Windows bug. We're caching the file under `file:///C:/Users/runneradmin/AppData/Local/Temp/.tmppQrNqo/wheels/ok-1.0.0-py3-none-any.whl`, but we then look for it later under `file:///C:/Users/RUNNER~1/AppData/Local/Temp/.tmppQrNqo/wheels/ok-1.0.0-py3-none-any.whl`.

**Comment by charliermarsh** [comment]
I'm going to skip this test on Windows while I fix it.

**Comment by charliermarsh** [comment]
(Just hid the counts and added a TODO.)

**Pull request merged**
