### PR TITLE
Add `uv build --no-build-logs` to silence the build backend logs

### PR DESCRIPTION
**Pull request by zanieb**
Extends https://github.com/astral-sh/uv/pull/7674

The build backend can be pretty verbose, it seems nice to be able to turn that off?

### CODE REVIEW

**Comment by charliermarsh** [comment]
This necessary given #7674? I'm just wary of adding more command-line flags without strong motivation.

**Comment by zanieb** [comment]
They're pretty distinct i.e. I want to be able to share the output of the command in the docs but the build backend output is a lot on a trivial project. Maybe this will be solved by #3957 ?

**Comment by charliermarsh** [comment]
Can you just use a `...` or similar in the docs? I guess I just don't see this as very useful in practice.

**Comment by zanieb** [comment]
Humph... easy enough to revisit if we need it later.

**Comment by charliermarsh** [comment]
Want to reopen? I somewhat prefer `--no-build-output` so that it doesn't require users to know what a "backend" is, but understand that `uv build --no-build-output` may be awkward.

**Review by charliermarsh — APPROVED** [review]

**Comment by zanieb** [comment]
> Want to reopen? I somewhat prefer `--no-build-output` so that it doesn't require users to know what a "backend" is, but understand that `uv build --no-build-output` may be awkward.

I felt the same thing and went back and forth. I figured it'd be better to be explicit since we don't foresee it being used by beginners? But `--no-build-output` sort of makes sense still... hm.

**Pull request merged**
