### PR TITLE
Improve performance of `MarkerTree::is_disjoint`

### PR DESCRIPTION
**Pull request by ibraheemdev**
## Summary

Resolves https://github.com/astral-sh/uv/issues/6137.

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
This makes sense! Does this improve perf on any resolutions?

**Comment by ibraheemdev** [comment]
I'm struggling to find complex resolution cases that are also consistent, but it does seem to be a small improvement in most cases.

**Comment by ibraheemdev** [comment]
Worked on this a little more and ran some microbenchmarks, this does seem to be a significant improvement, especially for markers that are *not* disjoint.
```
marker_disjointness     time:   [118.69 ns 119.12 ns 119.55 ns]
                        change: [-40.348% -40.036% -39.771%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  12 (12.00%) high mild

marker_disjointness_current
                        time:   [307.31 ns 307.92 ns 308.60 ns]
                        change: [-1.0642% -0.8529% -0.5884%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 18 outliers among 100 measurements (18.00%)
  15 (15.00%) low mild
  1 (1.00%) high mild
  2 (2.00%) high severe

marker_disjointness     time:   [308.82 ns 309.33 ns 309.85 ns]
                        change: [-49.069% -48.924% -48.768%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  1 (1.00%) low mild
  6 (6.00%) high mild
  1 (1.00%) high severe

marker_disjointness_current
                        time:   [1.2548 µs 1.2555 µs 1.2562 µs]
                        change: [-1.9563% -1.6812% -1.4606%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
  ```

**Comment by BurntSushi** [comment]
Nice win! Order of magnitude improvement in the second benchmark. Is that the case where the markers aren't disjoint?

**Comment by ibraheemdev** [comment]
Yup, that's when the markers are not disjoint, so the latter case ends up creating the conjoined markers that we just throw away.

**Pull request merged**
