### PR TITLE
Retain old python-build-standalone releases

### PR DESCRIPTION
**Pull request by zanieb**
Closes https://github.com/astral-sh/uv/issues/8213

I didn't mean to remove these when updating the regular expression. Arguably, they shouldn't be used anymore, but we should make that choice with intention.

### CODE REVIEW

**Comment by zanieb** [comment]
Wow it's actually horrible to try to construct the regex to match all these. We need to futz with a second lenient regex or just drop support.

**Review by charliermarsh — APPROVED** [review]

**Comment by zanieb** [comment]
Struggling to validate that this is "correct"

**Comment by notatallshaw-gts** [comment]
> Arguably, they shouldn't be used anymore, but we should make that choice with intention.

Two things from my point of view:

One, there is a strong use case for pinning against a patch version of Python, I have seen plenty of times where patch versions of Python breaks code, so I want to be able to control when a patch version is updated and test against it carefully.

Two, I would not expect a tool that installs my Python versions to *ever* make certain versions unavailable without announcing it as a big breaking change. This will be particularly important for large organizations, but if I have an internal app app running against Python 3.7.9, and everything is pinned, I not expect that to suddenly not work even if that app is still running against that version of Python in 10 years.

**Comment by zanieb** [comment]
>  I would not expect a tool that installs my Python versions to ever make certain versions unavailable without announcing it as a big breaking change. 

Definitely agree — this was an unintentionally removal due to the peculiarities of these old artifacts.

**Pull request merged**
