### PR TITLE
Add trace logs to `is_extended_transient_error`

### PR DESCRIPTION
**Pull request by zanieb**

### CODE REVIEW

**Comment by zanieb** [comment]
@charliermarsh still sort of into the idea of adding something like this, though we might need to include the error in the message.

**Comment by charliermarsh** [comment]
I can take over if you want, makes sense.

**Comment by zanieb** [comment]
All yours! I figure you have a better setup to test what's helpful here.

**Review by konstin — APPROVED** [review]

**Comment by charliermarsh** [comment]
Does this look ok?

**Pull request merged**
