### PR TITLE
Add license texts for contents of ecosystem/

### PR DESCRIPTION
**Pull request by musicinmybrain**
## Summary

While the contents of `ecosystem/` are “merely” `pyproject.toml` files and one trivial Python script, they are still covered by the licenses of the projects from which they are copied. Not only is maintaining license/copyright statements good practice, but it’s generally specifically required by the particular licenses involved here.

Even though these files are for integration testing only – and therefore do not contribute to the license of the compiled `uv` executable – they are nevertheless part of the source archive, so distributors and integrators need to consider their license status. For example, I maintain the `uv` package in Fedora Linux, and I need to consider these licenses because the files would be redistributed in the source RPMs.

## Test Plan

N/A – validated by examination of the diff.

### CODE REVIEW

**Comment by musicinmybrain** [comment]
I am not sure what to do about `prettier` complaining about `ecosystem/home-assistant-core/LICENSE.md`. The license is copied from `home-assistant-core` upstream, so it should not be modified or reformatted. Maybe I should rename it to `ecosystem/home-assistant-core/LICENSE`, dropping the somewhat dubious `.md` extension? That seems safe enough.

**Comment by zanieb** [comment]
There's an ignore file at: https://github.com/astral-sh/uv/blob/main/.prettierignore

**Comment by zanieb** [comment]
Thanks for taking the time to do this. I'll have @BurntSushi review since he added the tests :)

**Comment by musicinmybrain** [comment]
> There's an ignore file at: https://github.com/astral-sh/uv/blob/main/.prettierignore

Good suggestion – thanks! I added `ecosystem/home-assistant-core/LICENSE.md` to `.prettierignore`.

**Comment by musicinmybrain** [comment]
(I submitted the `pretix` license – the `AGPL-3.0-only` portion of which includes a custom exception – [for review by Fedora Legal](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/559). I’ll follow up in a separate issue if it’s found to be problematic.)

**Comment by BurntSushi** [comment]
> For example, I maintain the uv package in Fedora Linux, and I need to consider these licenses because the files would be redistributed in the source RPMs.

Can you why you're including them in the source RPMs? Why not exclude them?

**Comment by musicinmybrain** [comment]
> Can you why you're including them in the source RPMs? Why not exclude them?

The source RPM includes the `.spec` file that controls how the package is built, the original upstream source archive, and any patches or ancillary files. The original source archive is, e.g., https://github.com/astral-sh/uv/archive/0.2.37/uv-0.2.37.tar.gz (plus three more archives corresponding to the `async_zip`, `pubgrub`, and `reqwest_middleware` forks referenced by git hash in `Cargo.toml`), and so anything that’s in the git repository is in the source RPM. Note that we do run all of the tests that don’t require network access.

If I wanted to avoid distributing the `ecosystem/` directory, I would need to use a script to download the source archive from GitHub, remove `ecosystem/`, and then repack the source archive. Then, I would need to make sure I skipped running the tests that rely on those files; fortunately, those seem to be contained to `crates/uv/tests/ecosystem.rs`. All of this is perfectly feasible, and I maintain other packages in Fedora where this approach is necessary, but seems to be a bit of a heavyweight workaround for missing license texts. Alternatively, I *might* be able to switch to using the PyPI sdist, if it isn’t missing anything else I need.

While I doubt anyone is going to get upset about copying a `pyproject.toml` file in practice, in principle, maintaining the correct license texts for files copied from other projects and redistributed via GitHub would seem to be something that should matter to the `uv` project too, regardless of what downstream distribution packagers are doing.

**Comment by BurntSushi** [comment]
I think any tests involving things in the `ecosystem` directory are going to involve some kind of network I/O. At least, all extant tests do.

> While I doubt anyone is going to get upset about copying a pyproject.toml file in practice, in principle, maintaining the correct license texts for files copied from other projects and redistributed via GitHub would seem to be something that should matter to the uv project too, regardless of what downstream distribution packagers are doing.

I'm not a lawyer, so I'm not going to try to get into legal stuff here, but my mind is more headed in the direction of whether it's worth putting these tests in a different repository. Like, you really should not need to be getting AGPL license exemptions from lawyers in order to package `uv`. I don't want that to be a hurdle that folks feel like they need to cross, and if putting these tests in this repository provokes that hurdle, it might be something to rethink.

I suppose this is orthogonal to putting the license files in the repo. Since the legal aspect of this doesn't really change if we put them in another repo.

**Comment by musicinmybrain** [comment]
I think your analysis in https://github.com/astral-sh/uv/pull/6181#issuecomment-2296538198 is very reasonable.

**Comment by musicinmybrain** [comment]
> If I wanted to avoid distributing the `ecosystem/` directory, I would need to use a script to download the source archive from GitHub, remove `ecosystem/`, and then repack the source archive. Then, I would need to make sure I skipped running the tests that rely on those files; fortunately, those seem to be contained to `crates/uv/tests/ecosystem.rs`. All of this is perfectly feasible, and I maintain other packages in Fedora where this approach is necessary, but it seems to be a bit of a heavyweight workaround for missing license texts. […]

This – combined with applying this PR as a patch – is the approach I’m using to move forward for now, although I hope it won’t be permanent – either because the `pretix` license is found to be acceptable for Fedora, or because the contents of `ecosystem/` end up being moved out of this repository.

**Review by zanieb — APPROVED** [review]

**Comment by musicinmybrain** [comment]
> (I submitted the `pretix` license – the `AGPL-3.0-only` portion of which includes a custom exception – [for review by Fedora Legal](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/559). I’ll follow up in a separate issue if it’s found to be problematic.)

Just following up to say that the replacement of `pretix` with `saleor` in https://github.com/astral-sh/uv/pull/7567 due to https://github.com/astral-sh/uv/issues/7566 is really helpful, as now everything in `ecosystem/` has standard licenses.

**Pull request merged**
