### PR TITLE
Add `Seek` fallback for zip files

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Some zip files can't be streamed; in particular, `rs-async-zip` doesn't support data descriptors right now (though it may in the future). This PR adds a fallback path for such zips that downloads the entire zip file to disk, then unzips it from disk (which gives us `Seek`).

Closes https://github.com/astral-sh/uv/issues/2216.

## Test Plan

`cargo run pip install --extra-index-url https://buf.build/gen/python hashb_foxglove_protocolbuffers_python==25.3.0.1.20240226043130+465630478360 --force-reinstall -n`

### CODE REVIEW

**Comment by charliermarsh** [comment]
Somewhat torn on merging this. It's good behavior but it does add complexity, and `rs-async-zip` _might_ add data descriptor support soon (TBD).

**Comment by charliermarsh** [comment]
Eh, ultimately, this is a good thing to do.

**Comment by charliermarsh** [comment]
All these Windows tests are randomly overflowing their stacks is confusing to me. This shouldn't have changed the stack at all?

**Comment by konstin** [comment]
> All these Windows tests are randomly overflowing their stacks is confusing to me. This shouldn't have changed the stack at all?

Every local variable increases the stack frame size :sob:

**Comment by charliermarsh** [comment]
Nooooo

**Comment by charliermarsh** [comment]
It must be _so_ marginal

**Comment by konstin** [comment]
debug is just super inefficient with stack space, this never happens on release

**Pull request merged**
