### PR TITLE
Create lib64 symlink for 64-bit, non-macOS, POSIX environments

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/uv/issues/3578#issuecomment-2110675382.

## Test Plan

Verified that in the OpenSUSE test, we create both, and they're symlinks:

```text
INFO: Creating virtual environment with `venv`...
INFO: Installing into `venv` virtual environment...
DEBUG Found a virtualenv named .venv at: /tmp/tmp4nape29h/.venv
DEBUG Cached interpreter info for Python 3.10.14, skipping probing: .venv/bin/python
DEBUG Using Python 3.10.14 environment at .venv/bin/python
DEBUG Trying to lock if free: .venv/.lock
purelib: "/tmp/tmp4nape29h/.venv/lib/python3.10/site-packages"
platlib: "/tmp/tmp4nape29h/.venv/lib64/python3.10/site-packages"
is_same_file(purelib, platlib): Ok(true)
```

### CODE REVIEW

**Comment by konstin** [comment]
Code lgtm but it's odd because `virtualenv` doesn't create this directory for me

**Comment by charliermarsh** [comment]
Would you vote against merging? I tend to view `venv` as the reference implementation but also agree it's strange.

**Comment by charliermarsh** [comment]
@gaborbernat - sorry to bother, have you seen this before?

**Comment by gaborbernat** [comment]
Could be bug, I know Fedora creates two folders and should work.

**Pull request merged**
