### PR TITLE
Move off `reqwest-middleware` fork

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

The version we're pinned to got released!

### CODE REVIEW

**Comment by konstin** [comment]
we still need https://github.com/TrueLayer/reqwest-middleware/pull/159 to get merged before we can move off the fork

**Comment by charliermarsh** [comment]
Oh it's confusing that that's commit isn't on main, I missed it.

**Comment by konstin** [comment]
Good news, this is now merged: https://github.com/TrueLayer/reqwest-middleware/pull/159. We can update to the next release once out.

**Comment by charliermarsh** [comment]
Great!

**Pull request closed without merging**
