### PR TITLE
Use local package instead of `transitive_url_dependency.zip`

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
Time bomb

**Comment by charliermarsh** [comment]
I think it's still failing...

**Comment by zanieb** [comment]
GitHub down again?

**Comment by zanieb** [comment]
Put it on https://www.crmarsh.com/

**Comment by charliermarsh** [comment]
Lmao. Actually?

**Comment by zanieb** [comment]
Probably not haha 😁 ... maybe we should check it into a repository though? Like in `astral-test?

**Comment by zanieb** [comment]
Seems way more reasonable haha

**Pull request merged**
