### PR TITLE
Migrate lock errors to `thiserror`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Do we prefer this?

### CODE REVIEW

**Comment by charliermarsh** [comment]
I have a slight preference for it (it's so much more compact, and follows the idioms of the rest of the codebase), but I now need to box the variants.

**Review by konstin — APPROVED** [review]
Yes!

**Review by BurntSushi — APPROVED** [review]
I don't have strong feelings either way.

I've also been wondering if we should just switch to `anyhow::Error` (or similar) for most of our error handling. I'm not sure we really make use of our structured errors much. (And `anyhow::Error` doesn't preclude it, although it makes it a little more cumbersome.)

**Comment by charliermarsh** [comment]
I think my experience is similar: I actually prefer thiserror for uv because it forces us to think about and track the variants and how they’re used.

**Pull request merged**
