### PR TITLE
Support syncing for virtual workspaces

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Right now, `uv sync` and `uv run` fail when run from a virtual workspace. This PR adds support by syncing the entire workspace environment.

Closes https://github.com/astral-sh/uv/issues/4541.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Does this even make sense? A virtual workspace doesn't have any "dependencies". So what does it mean to run a command in a virtual workspace?

**Comment by charliermarsh** [comment]
I guess that's the crucial question: should you be able to `uv run` in a virtual workspace. The virtual workspace has no package, so it has no dependencies. It's not represented in the lockfile at all. So how would we sync it, if not by syncing the entire workspace?

**Comment by mjclarke94** [comment]
Could the run command make sense in the context of integration/cross-package tests?

Say you had a virtual workspace containing several namespace packages with their own isolated unit test suites. You could come up with a set of tests which only make sense in the context of having several of these packages installed at once.

**Comment by konstin** [comment]
The original design for workspaces to be centered around `uv run`, so that when you run an entrypoint from a package or a command in a package you would get only the dependencies from that package. My preferred way of handling this would be:
* Add `uv sync --package` (work like `--extra`, also `--all-packages`), that works like `uv run --package`
* Add a `tool.uv.default-packages = ["...", "..."]` setting (https://github.com/astral-sh/uv/issues/3625) for virtual workspaces that sets the default packages to install when running `uv sync` or `uv run`

**Comment by charliermarsh** [comment]
This got solved separately.

**Pull request closed without merging**
