### PR TITLE
Add upgrade note to README

### LINKED ISSUE #7858: Documentation: Add upgrade instructions to README
Hi there,
I noticed that the current README doesn't include instructions for upgrading `uv`. I think it would be helpful to have a small section below the "[Installation](https://github.com/astral-sh/uv?tab=readme-ov-file#installation)" section that explains how to upgrade the tool. I had some trouble finding the correct upgrade command and had to search through the documentation pages. 

Would it be possible to include this in the README? I'd be happy to contribute by submitting a small PR if needed :^)

Thanks!

### PR DESCRIPTION
**Pull request by Aditya-PS-05**
closes #7858 

## Summary
Added the upgrading uv section in README.  Added the ` uv self update` method and the `pip install --upgrade uv` method.

### CODE REVIEW

**Comment by zanieb** [comment]
I think this is too much content, the readme needs to stay small. I wonder if we can fit a succinct version in the section above?

**Comment by Aditya-PS-05** [comment]
Thanks for review, @zanieb, 
I will do it.

**Comment by Aditya-PS-05** [comment]
Hey @zanieb, 
I made the README more concise.

**Comment by Aditya-PS-05** [comment]
@zanieb , 
review?

**Pull request merged**
