### PR TITLE
[UX] Split README's install code block into 3

### PR DESCRIPTION
**Pull request by willingc**
- Broke up the large code block into 3 blocks so that copy paste icon works

Howdy Astral friends! This is a small PR which is a small user experience improvement for smooth installs.

### CODE REVIEW

**Comment by zanieb** [comment]
Won't the copy paste fail because of the leading `$` anyway?

**Comment by zanieb** [comment]
For some more context, in https://github.com/astral-sh/uv/issues/5397 we made it so that the `$` is stripped from copied console commands in the documentation but that doesn't apply to the README. I think we'll need to move the comments and `$` out of the code blocks to achieve the desired effect here.

Nice to see you Carol! Thanks for taking the time to contribute :)

**Comment by willingc** [comment]
I'm not sure about the $. But I figured that I would mention it since the copy paste grabbed all of lines and made the shell grumpy. Good to see you virtually too.

**Comment by zanieb** [comment]
I gave it a try [in the preview](https://github.com/astral-sh/uv/blob/7ab5f7676fa7533b2dbc124a8c8e25111b82302e/README.md#installation) and we'll need to change that before we can merge. I can futz with it sometime soon if you don't want to.

**Comment by willingc** [comment]
It does fail if you keep the preceding `$`.  I've removed the `$` and switched the syntax highlighting to `bash`. I'm able to copy-paste fine on Mac. YMMV on Windows (I don't have a good test machine for that.) @zanieb

**Comment by zanieb** [comment]
Thank you!

**Review by zanieb — APPROVED** [review]

**Pull request merged**
