### PR TITLE
`uv sync --no-clean`

### PR DESCRIPTION
**Pull request by ibraheemdev**
## Summary

Adds a `--no-clean` flag to `uv sync` that keeps extraneous installations. This is the default in `uv run` and `uv add`, but not in `uv sync` or `uv remove`. This means you need to run an explicit `uv sync/remove` to clean the virtual environment.

Could use some tests.

### CODE REVIEW

**Comment by zanieb** [comment]
I don't think we have a clear concept of "tracked" and it doesn't have a negative which follows our typical "no" prefix. I think a user could change the default sync behavior via configuration and want to opt-in to removal via the CLI and that should be natural.

Just to throw some ideas out....

- `--no-remove-untracked` / `--remove-untracked`
- `--allow-untracked` / `--no-allow-untracked`
- `--no-remove-extra-packages` / `--remove-extra-packages`
- `--no-remove-unknown` / `--remove-unknown` 
- `--no-clean` / `--clean`
- `--no-remove` / `--remove`
- `--untracked <remove | warn | ignore>`
- `--extra-packages <remove | warn | ignore>`

**Comment by zanieb** [comment]
@ibraheemdev can we separate fixing `run` and `add` so we can release without figuring out a name? Alternatively we can just use something and break it later if we want.

**Comment by ibraheemdev** [comment]
`--clean` and `--no-clean` are synonymous with commands from other tools (`cargo clean`), so I think that makes sense for now.

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
It's a little weird because it refers to the cache in those cases but the actual environment in this one. I'm fine to try it out though.

**Comment by ibraheemdev** [comment]
There's also `pdm sync --clean`.

**Comment by zanieb** [comment]
That's where I saw it :D

**Pull request merged**
