### PR TITLE
`uv pip list`

### PR DESCRIPTION
**Pull request by sbrugman**
Hi, love your work on `uv` 👋! 

Opening a Draft PR early to check if there are any existing rust table formatting libs that I am unaware of (either already in `uv`/`ruff`, or the rust ecosystem) before spending much time on inventing the wheel myself and cleaning it up. Any other pointers are also welcome (e.g. on the editable filtering).

Editable project locations in `uv pip list` include the file scheme (`file://`), where they are omitted in `pip list`. Is this desired, or should it replicate pip?

## Summary

Implementation for #1401 
`--editable` flag is implemented.

`--outdated` and `--uptodate` out of scope for this PR (requires latest version information, and type wheel/sdist)

## Test Plan

Not yet implemented as I couldn't locate the tests for `uv pip freeze`.
We can compare to `pip` in `scripts/compare_with_pip/compare_with_pip.py`?

### CODE REVIEW

**Comment by charliermarsh** [comment]
I think it's fine for us to write our own table-formatting logic (@MichaReiser tends to have good opinions on when we should use a crate vs. do things ourselves). I don't feel strongly about `file://` but my initial reaction is that it'd be nice to strip them.

**Comment by charliermarsh** [comment]
Great to see you on the repo @sbrugman, hi again!

**Comment by sbrugman** [comment]
@BurntSushi Does self-assigning mean you will take it from here or shall I still continue?

**Comment by sbrugman** [comment]
Thanks for the reply and the pointer. I'll continue with `tabwriter` (great to see the Springsteen references 😄 ) and test consistency with `pip list`

**Comment by sbrugman** [comment]
@BurntSushi `tabwriter` misses functionality for the border below the header. We need it to replicate `pip list`:
```text
Package                    Version         Editable project location
-------------------------- --------------- ---------------------------------------
aiohttp                    3.8.1
aiosignal                  1.3.1
(...)
```

Assuming it's not in scope to extend `tabwriter` (correct me if wrong), I can check out some other packages, e.g.:
https://docs.rs/cli-table/latest/cli_table/
https://docs.rs/papergrid/latest/papergrid/

**Comment by BurntSushi** [comment]
Ah yeah, `tabwriter` is pretty basic. It really only does tab expansion.

If it were me, I'd probably just hand code it:

1. Build each column in a `Vec`.
2. Find the max width of each column using [`unicode-width`](https://docs.rs/unicode-width/latest/unicode_width/).
3. Insert padding and the dashed lines as appropriate.

It shouldn't be much code and shouldn't be too tricky to write.

**Comment by sbrugman** [comment]
@BurntSushi Took a bit longer than hoped, ready for review! The `--outdated` and `--uptodate` flags can be added later in follow-up work, as they require latest version and type (wheel/sdist) information.

**Comment by charliermarsh** [comment]
Thanks @sbrugman!

**Comment by sbrugman** [comment]
Windows test fixed. 

Turned out that the Windows `file:///` prefix has an additional forward slash. Changed the tests to support workdir paths to be shorter than the replacement (as is the case on Windows). Finally needed to change the filter order to start with `INSTA_FILTERS` to rewrite Windows paths before replacement.

There are some more args that we could implement after the basic functionality is merged.

**Review by charliermarsh — APPROVED** [review]
Excellent!

**Pull request merged**
