### PR TITLE
Prefer smaller wheels when priority is unset

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/uv/issues/7216.

### CODE REVIEW

**Comment by konstin** [comment]
Files an issue upstream for the tensorflow problem: https://github.com/tensorflow/tensorflow/issues/75415

Imo this is blocking since it breaks tensorflow.

**Comment by charliermarsh** [comment]
Is the new resolution any more wrong / right than the old?

**Comment by konstin** [comment]
The windows package is a stub, just forwarding to `tensorflow-intel`, while the unix package is a real tensorflow package that users want to install and whose deps users want to have, so i consider the unix one more correct.

**Comment by charliermarsh** [comment]
That makes sense, thanks @konstin. Do you think the heuristic is a lost cause? Or should we special-case TensorFlow in some way? Something else?

**Comment by konstin** [comment]
Either way we choose, i believe tensorflow should consolidate their metadata, since coherent metadata is a core assumption in universal resolvers such as poetry. What we do with the PR depends on how much problems the current heuristic causes for our users: If the current behaviour causes trouble, add a workaround for tensorflow and merge. If it doesn't, i'd favor not adding package-specific workarounds and wait until tensorflow has fixed their metadata and that propagated through the ecosystem (and then doing this change).

**Comment by charliermarsh** [comment]
I don't think it's necessarily causing problems. It can wait (at least for a response). But it will continue to be wrong for older versions no matter what.

**Pull request closed without merging**
