### PR TITLE
ci: add musl ppc64le

### PR DESCRIPTION
**Pull request by henryiii**
## Summary

Working on followup to #3523. I expect some changes will be required to match the glibc versions above.

### CODE REVIEW

**Comment by henryiii** [comment]
I'm not sure how to cross-compile for these targets. Binaries are not provided, AFAICT, so I think the target needs to be built. I vaguely have clues on how to do that, but not sure how to inject my ideas into maturin-action.

**Comment by charliermarsh** [comment]
@konstin or @messense may have ideas.

**Comment by henryiii** [comment]
It looks like there's mention of the powerpc64le one in maturin-action, so I was rather thinking that might work. s309x is sounds like it's not possible currently. I'm checking to see if missing uv on these two (I would assume) rarely used images is acceptable in manylinux.

**Comment by messense** [comment]
ppc64le musl requires Rust nightly, I have tried to build a Docker image for s390x musl in the past, but it seems to have some issues (see https://github.com/rust-cross/rust-musl-cross/issues/63) so I haven't added it to `maturin-action`.

**Comment by henryiii** [comment]
Great! Only musl s390x (and Windows ARM) left!

Is https://github.com/rust-cross/rust-musl-cross/issues/63 still an issue? Looks like it's been a while since it was attempted?

**Comment by messense** [comment]
> Is [rust-cross/rust-musl-cross#63](https://github.com/rust-cross/rust-musl-cross/issues/63) still an issue? Looks like it's been a while since it was attempted?

Probably still an issue, but I think it's solvable given that Alpine Linux has the target working for years now, although it's a hard problem for people without deep knowledge in GCC.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
