### PR TITLE
docs `docker.md`: example to use bind mounts

### PR DESCRIPTION
**Pull request by odie5533**
## Summary

Update the extended docker example to use bind mounts and avoid creating extra layers and avoid copying files into layers

This is in line with the official Docker templates for Python applications (you can try them out using `docker init`. I found them very helpful!)

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thank you! Tagging @zanieb for review.

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
If you're interested, this could be changed over in https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile too!

**Comment by konstin** [comment]
How does this interact with caching, will `uv sync --frozen --no-install-project` rerun when `uv.lock` changed? https://docs.docker.com/engine/storage/bind-mounts/ doesn't talk about caching and https://docs.docker.com/build/cache/ doesn't say anything about mounts.

**Comment by odie5533** [comment]
> How does this interact with caching, will `uv sync --frozen --no-install-project` rerun when `uv.lock` changed? https://docs.docker.com/engine/storage/bind-mounts/ doesn't talk about caching and https://docs.docker.com/build/cache/ doesn't say anything about mounts.

It has the same behavior as would adding them to the layer, so if `uv.lock` or `pyproject.toml` changes it will re-run the layer (re-run `uv sync --frozen --no-install-project`).

**Pull request merged**
