### PR TITLE
Detect nested workspace inside the current workspace and members with identical names

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Align uv's workspace discovery with red knots (see https://github.com/astral-sh/ruff/pull/14308#issuecomment-2474296308)

* Detect nested workspace inside the current workspace rather than testing if the current workspace is a member of any outer workspace. 
* Detect packages with identical names.

## Test Plan

I added two integration tests. I also back ported the tests to main to verify that both these invalid workspaces aren't catched by uv today. That makes this, technically, a breaking change but I would consider the change a bug fix.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thanks king! I should've clarified that I was also willing to do this if we shipped the version you have in red-knot, but I'm grateful to you for PRing it.

**Comment by charliermarsh** [comment]
I can do the testing etc. if you need.

**Comment by MichaReiser** [comment]
I can do it tomorrow but let me know if you have any suggestions on how/where to add automated tests for this.

**Review by charliermarsh — APPROVED** [review]
Very nice, thanks Micha!

**Pull request merged**
