### PR TITLE
Perform source distribution builds in archive directory

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This is an attempt to help with https://github.com/astral-sh/uv/issues/7078 by reducing the length of cache paths on Windows. It needs some testing on my Windows machine though.

### CODE REVIEW

**Comment by zanieb** [comment]
This is just something to help right? Not the "real" long term fix?

**Comment by charliermarsh** [comment]
> Not the "real" long term fix?

Sorry, what would this be? There's a fundamental path length limit. All we can do is help, I don't think there is a real fix.

**Comment by zanieb** [comment]
I was thinking about how we previously talked about using a hash instead of a wheel file name in the cache. Looking at the linked issue I see this looks like a separate file length issue than that though.

**Comment by charliermarsh** [comment]
Oh sorry, yes! That's a separate issue, I don't think this will help with that sadly.

**Comment by zanieb** [comment]
No problem I should have looked at the issue or read more closely. Thanks for clarifying!

**Pull request closed without merging**
