### PR TITLE
include testing on amazonlinux:2023

### PR DESCRIPTION
**Pull request by altendky**
Trying to test related to https://github.com/astral-sh/uv/issues/1532.

### CODE REVIEW

**Comment by BurntSushi** [comment]
This LGTM, but I'll defer to @charliermarsh or @zanieb on whether we want to add new CI jobs.

**Comment by altendky** [comment]
If it is wanted, I can bother to make it actually work.  Or you can go ahead and close it.

**Comment by zanieb** [comment]
CI is kind of expensive, I'm hesitant to add more jobs. We'll talk about this some more though.

**Comment by altendky** [comment]
Not a big deal to me, just figured I'd offer it.  I'm used to running lots on free runners.  If you want it but want to keep costs down there could be a nightly group or somesuch.

**Comment by zanieb** [comment]
@altendky I'm willing to accept this, I think. We can add a guard like

`if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'extended-platforms')`

I'm happy to do that separately if you get it working.

**Comment by altendky** [comment]
Sounds good, I'll try to get it ready for you.  Rocky or Fedora might actually be more interesting, possibly, but I don't know how people tend to deploy what where.  I just happened to pick amazonlinux from the failures I had seen.

**Comment by zanieb** [comment]
I figure we can have extended coverage for more platforms too in the future, e.g. alpine seems important.

**Comment by zanieb** [comment]
I ended up doing this.

**Comment by altendky** [comment]
Thanks for following through, and my apologies for leaving it hanging.  I appreciate how prompt you all have been around my queries here.

**Pull request closed without merging**
