### PR TITLE
Display portable paths in posix venv activation commands

### LINKED ISSUE #5950: Activation prompt with invalid path on Windows Git Bash
Windows 11, uv 0.2.34 (c681c5a33 2024-08-07)

Activating a environment after creating it:

$ uv v
Using Python 3.12.0 interpreter at: C:\Users\MaagB\AppData\Local\Programs\Python\Python312\python.exe
Creating virtualenv at: .venv
Activate with: source .venv\Scripts\activate

$  source .venv\Scripts\activate
bash: .venvScriptsactivate: No such file or directory

Problem:
git bash on windows seems to resolve the escape sequences before making the source call. To properly activate the environment we either need to properly espace the backslash by another backslash:

$ source .venv\\Scripts\\activate
(tmpinstall)

Or use the Unix Path:
$ source .venv/Scripts/activate
(tmpinstall)

### PR DESCRIPTION
**Pull request by zanieb**
Closes #5950

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Will this get correctly detected as Posix on Windows Git Bash?

**Comment by charliermarsh** [comment]
I can probably test it.

**Comment by zanieb** [comment]
I'm pretty sure, but I'd appreciate if you tested it.

**Comment by charliermarsh** [comment]
Will do.

**Comment by charliermarsh** [comment]
Confirmed that this works.

**Comment by chourroutm** [comment]
Hi! Sorry, I don't understand how to have uv recognized for the Git for Windows Bash. Do I need to append uv binaries to the Windows env var PATH?

**Pull request merged**
