### PR TITLE
Add test for avoiding irrelevant extras

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR adds a test that currently leads to an error, but should successfully resolve as of https://github.com/astral-sh/uv/pull/3100.

The core idea is that if we have a pinned package, we shouldn't try to build other versions of that package if we have an unconstrained variant with an extra.

### CODE REVIEW

**Comment by zanieb** [comment]
I wish we could do these without committing tarballs so we could see the source code, but it doesn't seem worth calling a real build backend from the test... unless we had a little one in Rust.

**Comment by charliermarsh** [comment]
Yeah. I could commit... both? But I agree.

**Comment by charliermarsh** [comment]
I assume you say that from both a security and clarity/code-review perspective.

**Comment by zanieb** [comment]
Both plus the script used to generate the tarballs seems like the simplest path forward for now.

**Review by konstin — APPROVED** [review]

**Pull request merged**
