### PR TITLE
Disallow `pyproject.toml` files for non-project configuration

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We already _don't_ discover a `pyproject.toml` in `~/.config/uv` -- it must be `uv.toml`. This PR makes the same change for `--config-file` -- it _has_ to be a `uv.toml`.

I think this is reasonable and more consistent, though I'm not sure. A `pyproject.toml` "means" something -- it defines a project itself, in which case we should be using project configuration. But creating a `pyproject.toml` outside the project and passing it via `--config-file` seems like an anti-pattern.

### CODE REVIEW

**Comment by zanieb** [comment]
Is there another way to change the "root" of the invocation to a different `pyproject.toml` than the working directory? That might address this use-case. I see `--config-file foo/pyproject.toml` as a desire to change the target entirely rather than just change the config. What does Cargo do here? It allows `--config foo/Cargo.toml` afaik.

**Comment by charliermarsh** [comment]
I think Cargo allows `--config foo/config.toml`, which isn't the same as a `Cargo.toml`, unless I'm mistaken?

**Comment by zanieb** [comment]
Oh okay nevermind regarding Cargo you're totally right.

**Comment by charliermarsh** [comment]
I think... I've never had a need to really internalize the difference.

**Comment by zanieb** [comment]
Yeah I checked the docs https://doc.rust-lang.org/cargo/reference/config.html

**Review by zanieb — APPROVED** [review]

**Pull request merged**
