### PR TITLE
Add loongarch64 to supported Python platform tags

### PR DESCRIPTION
**Pull request by wojiushixiaobai**

### CODE REVIEW

**Comment by charliermarsh** [comment]
Have you tested this on an applicable machine?

**Comment by wojiushixiaobai** [comment]
@charliermarsh 
Sorry, I forgot to add the description,
I'm testing the functionality of the loongarch64 architecture, I'll add the results to the reply once the test passes.

**Comment by charliermarsh** [comment]
Okay thanks. Just comment here when you've had a chance to test + updated the summary!

**Comment by wojiushixiaobai** [comment]
@charliermarsh 
Test passed successfully.

```sh
root@85348a55bc91:/opt/test# uv init
Initialized project `test`
root@85348a55bc91:/opt/test# uv add django
Using CPython 3.12.8 interpreter at: /usr/local/bin/python3.12
Creating virtual environment at: .venv
Resolved 5 packages in 986ms
Prepared 3 packages in 1.23s
Installed 3 packages in 281ms
 + asgiref==3.8.1
 + django==5.1.4
 + sqlparse==0.5.3
root@85348a55bc91:/opt/test# uv python find --verbose
DEBUG uv 0.5.13
DEBUG Found project root: `/opt/test`
DEBUG No workspace root found, using project root
DEBUG Reading Python requests from version file at `/opt/test/.python-version`
DEBUG Using Python request `3.12` from version file at `.python-version`
DEBUG Searching for Python 3.12 in virtual environments, managed installations, or search path
DEBUG Found `cpython-3.12.8-linux-loongarch64-gnu` at `/opt/test/.venv/bin/python3` (virtual environment)
/opt/test/.venv/bin/python3
```

image

**Comment by charliermarsh** [comment]
Thanks!

**Pull request merged**
