### PR TITLE
Add basic tests for lockfile generation

### PR DESCRIPTION
**Pull request by charliermarsh**

### CODE REVIEW

**Comment by charliermarsh** [comment]
@BurntSushi - do you find this useful or intrusive?

**Comment by charliermarsh** [comment]
(Alternatively, I can write these as `uv lock` and `uv sync` invocations if we want, it just requires more work to get all the options like `--exclude-newer` threaded down.)

**Review by BurntSushi — APPROVED** [review]
I think it's useful! We'll certainly need something like this.

I think my main concern here is the encoding of the `--unstable-uv-lock-file` flag in tests. Because we want to remove that ~soonish. But I think these tests are probably simple/straight-forward enough that we ought to be able to migrate them to Blue Jay without much fuss.

**Comment by charliermarsh** [comment]
Sounds good -- I can also mechanically migrate them to `uv lock` and `uv sync`, it just requires adding support for (e.g.) `--exclude-newer`.

**Pull request merged**
