### PR TITLE
Escape Windows paths with spaces in `venv` activation command

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Ensure that we print `& "foo bar\Scripts\activate"` if necessary.

### CODE REVIEW

**Comment by samypr100** [comment]
@charliermarsh In cmd.exe it would just be "foo bar\Scripts\activate" instead of `& "foo bar\Scripts\activate"`, so maybe doing something like
`format!("& \"{executable}\" (PS) or \"{executable}\" (CMD)")` would suffice given shell detection on windows is not very friendly?

**Comment by charliermarsh** [comment]
Yeah I can't figure out how to detect if it's PowerShell or CMD... Do you know of any way to do it?

**Comment by samypr100** [comment]
From an env perspective? Not that I'm aware of unfortunately. I did see some code rely on `PSModulePath` for powershell detection by parsing it's value and checking it contains more than 3 entries (see https://stackoverflow.com/a/55598796)
which basically does `is_power_shell = len(os.getenv('PSModulePath', '').split(os.pathsep)) >= 3 `.

It's heuristic because a user could potentially modify PSModulePath to their system environment variables and it would break this detection, but without modifications it would work since PowerShell itself modifies PSModulePath on launch [per docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables) and always prefixes three entries on startup (regardless of system env) since it's a special PowerShell variable.

**Comment by samypr100** [comment]
Thinking about the oposite angle (which might be simpler), an asnwer on the same SO also mentions cmd.exe always defines `PROMPT` where as PowerShell does not, so maybe we can rely on that to detect cmd.exe and fallback to PS? https://stackoverflow.com/a/66415037

**Comment by samypr100** [comment]
Example implementation of last comment in https://github.com/astral-sh/uv/pull/2226

**Pull request merged**
