### PR TITLE
Allow installation of manylinux wheels on riscv64

### PR DESCRIPTION
**Pull request by markdryan**
## Summary

auditwheel is capable of generating riscv64 wheels for manylinux_2_31 and above.  Here we modify uv-platform-tags so that those wheels can be installed using uv.

Fixes: #8889

## Test Plan

- ran `cargo nextest run` locally on an x86 machine
- also ran `cargo nextest run` locally on a riscv64 VM but there were a fair few failures (with and without this patch)
- built a riscv64 uv wheel, installed it on a riscv64 VM and checked that I could use the newly built version of uv to install manylinux_2_35_riscv64 wheels.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Are you able to link to any references around the riscv64 / manylinux relationship, for posterity?

**Comment by konstin** [comment]
It's documented in https://github.com/pypa/auditwheel/blob/dd3df250063f520950f7f7c3e30544c701b5ec9c/src/auditwheel/policy/manylinux-policy.json#L329, i wanted to add this for the review

**Comment by markdryan** [comment]
> Are you able to link to any references around the riscv64 / manylinux relationship, for posterity?

There's a [thread](https://discuss.python.org/t/packaging-support-for-riscv64/58475) discussing the status of packaging support for riscv64 in the Python packaging discussion forums.  As far as I'm aware, the situation as of today is that, auditwheel>=6.10 and maturin>=v1.7.1 can create manylinux riscv64 wheels and pip>=24.1 can install them.  Neither the manylinux container images, pypi/wharehouse or cibuildwheel yet support riscv64, but this doesn't in itself prevent riscv64 manylinux wheels from being built, installed or uploaded to other registries, such as those provided by gitlab.

**Review by konstin — APPROVED** [review]
Thanks!

I've confirmed with `docker run --rm -it --platform linux/riscv64 ubuntu` that `uv pip install cmake --only-binary :all: -v --index-url https://gitlab.com/api/v4/projects/riseproject%2Fpython%2Fwheel_builder/packages/pypi/simple` picks the manylinux over the linux package after this change

**Pull request merged**
