### PR TITLE
uv/tests: add new 'ecosystem' integration tests

### PR DESCRIPTION
**Pull request by BurntSushi**
At a high level, this PR adds a smattering of new tests that
effectively snapshot the output of `uv lock` for a selection of
"ecosystem" projects. That is, real Python projects for which we expect
`uv` to work well with.

The main idea with these tests is to get a better idea of how changes
in `uv` impact the lock files of real world projects. For example,
we're hoping that these tests will help give us data for how #5733
differs from #5887.

This has already revealed some bugs. Namely, re-running `uv lock` for a
second time will produce a different lock file for some projects. So to
prioritize getting the tests added, for those projects, we don't do the
deterministic checking.

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Great idea.

**Comment by zanieb** [comment]
Could we note in a README or something what commits these were pulled from for each project?

**Review by zanieb — APPROVED** [review]

**Comment by BurntSushi** [comment]
I marked the `warehouse` and `transformers` tests to run on Linux only. The former because it seems to rely on running `pg_config` (so I'm not sure how one would produce a universal resolution on, say, Windows) and the latter because it times out on macOS/Windows.

**Comment by konstin** [comment]
I love having ecosystem test for the universal resolver!

Are there options to trim them down? 30k lines is a lot.

**Comment by zanieb** [comment]
Alternatively, we could have them in a separate repository and test them in a separate workflow than `cargo test`?

**Comment by BurntSushi** [comment]
> I love having ecosystem test for the universal resolver!
> 
> Are there options to trim them down? 30k lines is a lot.

I can't think of one. You could compress them, but then you inhibit human readability.

@zanieb I'm not a huge fan of having them in a separate repo if we can avoid it, mostly because I think it's a big pain to have tests hosted elsewhere. Then any updates need multiple PRs. And we're already doing that for packse scenarios.

**Pull request merged**
