### PR TITLE
Ignore `.python-version` files in `uv venv` with `--no-config`

### PR DESCRIPTION
**Pull request by zanieb**

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
I know we these files in one of the `uv python` APIs -- does that use the same arguments?

**Comment by zanieb** [comment]
Like in #6369 ?

**Comment by charliermarsh** [comment]
I'm thinking of `--no-workspace` in `uv python pin`.

**Comment by zanieb** [comment]
Added #6514

**Pull request merged**
