### PR TITLE
Add constraint dependencies to pyproject.toml

### LINKED ISSUE #4467: Support `constraints` in `pyproject.toml`
Similar to the override support we added, we should probably also support constraints? It seems nice to allow you to avoid an upper-bound in your published metadata, but add one for locking.

### PR DESCRIPTION
**Pull request by Di-Is**
Resolves #4467.

## Summary

This PR implements the following

1. Add `tool.uv.constraint-dependencies` to pyproject.toml
1. Support to refer `tool.uv.constraint-dependencies` in `uv lock`
1. Support to refer `tool.uv.constraint-dependencies` in `uv pip compile/install`

These are analogues of the override features implemented in #3839 and #4369.

## Test Plan

Add test.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Thanks, this is looking great! Do you mind adding the analogous changes to `crates/uv/src/settings.rs`? See `overrides_from_workspace`.

**Comment by Di-Is** [comment]
I modified `crates/uv/src/settings.rs` to reference `tool.uv.constraint-dependencies`.

**Review by charliermarsh — APPROVED** [review]
Thank you.

**Comment by purajit** [comment]
Incredible! We had one use-case where we might have been forced to use the pip interface, I didn't see anything in the docs, but luckily Google surfaced this PR! Works perfectly.

**Pull request merged**
