### PR TITLE
Drop "written in Rust" from docs landing

### PR DESCRIPTION
**Pull request by zanieb**

### CODE REVIEW

**Comment by zanieb** [comment]
Requested by @BurntSushi — and I agree.

**Review by BurntSushi — APPROVED** [review]
I approve my own request.

**Comment by ibraheemdev** [comment]
Do we want to highlight anything other than "fast"?

**Comment by charliermarsh** [comment]
Not strongly opposed but what's the problem with this? I feel like it's nice to have consistency in this copy across various sources.

**Comment by zanieb** [comment]
I agree consistency seems nice, but I'm kind of against having this marketing copy in the documentation and CLI descriptions. We already dropped this in the CLI:

```
❯ uv help
An extremely fast Python package manager.
```

I think it makes more sense in blog posts and the README?

**Comment by zanieb** [comment]
Okay, cheesy I know but let's bias towards retaining this — if we had a marketing team they'd probably make us :)

**Pull request closed without merging**
