### PR TITLE
Add `tool dir` and `toolchain dir` commands

### LINKED ISSUE #4483: Add `uv toolchain dir`
Similar to `uv cache dir`, displays the path to the toolchain directory.

### LINKED ISSUE #4484: Add `uv tool dir`
Similar to `uv cache dir`, displays the directory we install tools to

### PR DESCRIPTION
**Pull request by blueraft**
## Summary

Resolves #4483 
Resolves #4484 

## Test Plan

`cargo test`

```sh
❯ cargo run -- toolchain dir
warning: `uv toolchain dir` is experimental and may change without warning.
/Users/ahmedilyas/Library/Application Support/uv/toolchains

❯ cargo run -- tool dir
warning: `uv tool dir` is experimental and may change without warning.
/Users/ahmedilyas/Library/Application Support/uv/tools
```

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Thank you! That's perfect.

**Comment by blueraft** [comment]
Uh tests failed I'll check 🤔

**Comment by charliermarsh** [comment]
It looks like something frustrating with the filters. Maybe try running without `context.filters()` to see what's happening?

**Comment by charliermarsh** [comment]
That seems ok to me... `user_display` just truncates if it's relative, which is rare for these cases (and probably not desired anyway).

**Comment by charliermarsh** [comment]
Can you change `cache dir` as well for consistency?

**Comment by blueraft** [comment]
Done

**Pull request merged**
