### PR TITLE
Treat Python version as a lower bound in `--universal`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/uv/issues/4591.

### CODE REVIEW

**Review by konstin — APPROVED** [review]

**Comment by konstin** [comment]
Do we have an issue for considering `requires-python` when using `uv pip compile --universal pyproject.toml`?

**Comment by charliermarsh** [comment]
We don't, but I'm undecided on whether we should... Probably? But it would mean that the `uv pip` API now reads from your "project" which it doesn't do today. (Maybe fine but blurs some boundaries.)

**Comment by konstin** [comment]
I thought about discovering `pyproject.toml` but i think we shouldn't for that reason, but when we're already reading `project.dependencies` i think we can also read `project.requires-python`. Not high-priority though.

**Comment by zanieb** [comment]
I agree with that logic :)

**Review by zanieb — APPROVED** [review]

**Pull request merged**
