### PR TITLE
Add `uv add --no-editable`

### LINKED ISSUE #5241: Should uv add have editable as a flag
Current cli interface for editable like this:

```uv add --editable true depencency```

I think ```uv add --editable```  and ```uv add --no-editable``` with no true/false value would be more familiar to most people?

Feel free close if it doesn't make sense.

### PR DESCRIPTION
**Pull request by j178**
## Summary

Resolves #5241

## Test Plan

```sh
# create a workspace with sub-packages `pkg-a` and `pkg-b`

$ cd ./pkg-b
$ cargo run -- add ./pkg-a --no-editable

$ cat ./pyproject.toml
[project]
name = "pkg-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "pkg-a",
]

[tool.uv]
dev-dependencies = []

[tool.uv.sources]
pkg-a = { workspace = true, editable = false }
```

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Thanks!

**Comment by zanieb** [comment]
@charliermarsh this was implemented intentionally as `--editable` and `--editable=true` / `--editable=false` to match the syntax you'd use in the lock file. I don't prefer `--no-editable`.

cc @ibraheemdev

**Comment by charliermarsh** [comment]
I don't understand why you would use `--editable=true`, that's so surprising!

**Comment by charliermarsh** [comment]
Oh, you're saying `--editable` already worked, but it _also_ supported `--editable=true` and `--editable=false`? I don't know, that's also not as intuitive to me given that we don't have that pattern anywhere else in the CLI.

**Comment by zanieb** [comment]
Yeah because of `default_missing_value = "true"`.

I know it's not aligned with the rest of the CLI — but it does directly match the `sources` definition. I don't know if I feel particularly strongly, but wanted to flag that this wasn't an oversight. I'm not sure why, but `--no-editable` doesn't feel like it encodes the meaning as clearly (although it is more intuitive given our _existing_ patterns).

**Comment by charliermarsh** [comment]
Ok I defer to others on this (you and @ibraheemdev). I also don't feel strongly. I thought the original report was that you had to do `--editable=true` which I knew every user would get wrong :)

**Comment by zanieb** [comment]
Maybe the most user-friendly thing is to support `--editable` / `--no-editable` and `--editable=true` / `--editable=false`. It's not like there's something else we'll want the flag for. 

Are there other booleans that would make sense as `--<name>=false` (instead of `--no-<name>`)?

I'll think on this. Unsure if we should revert in the meantime.

**Comment by bluss** [comment]
Sorry for this one then.

I'll chime in and say the reason I reported the bug was this interaction:

```
> uv add --editable ./sibling/
error: invalid value './sibling/' for '--editable [<EDITABLE>]'
```

So just `--editable` works in some places but not before the name of the dependency.

**Comment by charliermarsh** [comment]
Ahh yeah. That's actually a pretty big footgun in my opinion.

**Comment by zanieb** [comment]
Ah okay sold. Thanks!

**Pull request merged**
