### PR TITLE
Upgrade packse to 0.3.15

### PR DESCRIPTION
**Pull request by zanieb**
Includes https://github.com/astral-sh/packse/pull/179 for #3225

```
uv pip compile scripts/scenarios/requirements.in -o scripts/scenarios/requirements.txt --refresh-package packse --upgrade
cargo dev fetch-python
source .env
./scripts/sync_scenarios.sh
```

### CODE REVIEW

**Comment by konstin** [comment]
This needs a `BUILD_VENDOR_LINKS_URL` update too, should we add that to the script?

**Comment by zanieb** [comment]
Ah thanks for the note. We probably should!

**Comment by zanieb** [comment]
We could add a separate `upgrade-packse` script that runs the requirements update and does this replacement?

**Review by ibraheemdev — APPROVED** [review]
Looks good after `BUILD_VENDOR_LINKS_URL` is updated.

**Pull request merged**
