### PR TITLE
Add wget instructions for systems without curl

### PR DESCRIPTION
**Pull request by joshmcorreia**
## Summary
Adds wget instructions for linux installations that don't come with `curl`.

## Test Plan
This was tested on Ubuntu 20.04, Ubuntu 22.04, Ubuntu 24.04, and Debian 11.

### CODE REVIEW

**Comment by zanieb** [comment]
We want to keep the README as small as possible here. Maybe in the documentation Installation guide instead? I'm a bit hesitant though.

**Comment by zanieb** [comment]
Thanks for contributing to the project :)

**Comment by joshmcorreia** [comment]
> Maybe in the documentation Installation guide instead? I'm a bit hesitant though.

Is there a reason you're hesitant to add it to the installation guide?

**Comment by zanieb** [comment]
It's just more content for people to read and it hasn't come up so far.

**Comment by joshmcorreia** [comment]
It came up for me on a docker container without curl and I created the PR because there wasn't any existing documentation on it. Up to you on if you want to close it or not - at least if someone else faces the same problem as me they'll be able to search "wget" and find this solution.

**Comment by samypr100** [comment]
@joshmcorreia Indeed, I think it's still worth adding possibly as a note in https://github.com/astral-sh/uv/blob/main/docs/index.md instead of the repo README.

**Pull request merged**
