### PR TITLE
Only remove a source from `[tool.uv.sources]` if it is no long being referenced

### LINKED ISSUE #8361: Only remove `[tool.uv.sources]` during `uv remove` when no longer relevant
e.g., as demonstrated by https://github.com/astral-sh/uv/pull/8360 we remove the sources entry on the first `uv remove` call even though the dependency is still required in the `optional-dependencies` and `dev-dependency` sections.

### PR DESCRIPTION
**Pull request by j178**
## Summary

Resolves #8361

### CODE REVIEW

**Comment by zanieb** [comment]
I finally got #8360 past the flaky CI which should cover this case.

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
Thanks again!

**Comment by zanieb** [comment]
Awkwardly, sources can be defined for transitive dependencies so we might need to check that it's not present in the resolution?

https://github.com/astral-sh/uv/issues/7454#issuecomment-2355710565

Relatively niche, but someone will notice eventually.

cc @charliermarsh

**Comment by charliermarsh** [comment]
I believe sources are only respected for dependencies defined in the workspace, not arbitrary transitive dependencies.

**Pull request merged**
