### PR TITLE
fix bug where MarkerTree::is_disjoint was sometimes not commutative

### PR DESCRIPTION
**Pull request by BurntSushi**
This PR fixes a bug where disjointness checking didn't always
satisfy commutativity. And it *should*. The `is_disjoint_commutative`
test added here demonstrates a regression test. Before this commit,
its second assertion failed.

That is, given `m1 = extra == "A" and extra != "B"` and
`m2 = extra == "A"`, we were saying that m1 was disjoint with
m2 (wrong) but that m2 was not disjoint with m1 (right).

It turned out that this was a "simple" matter of not using the
correct parent node when calling negation. Likely just a
transcription snafu.

This bug does not seem restricted in scope to extras, which is
how I found it, so it's not clear why we haven't noticed it until
now. I noticed it because I was formulating markers in a similar
format for resolver forking based on conflicting extras, and this
resulted in incorrectly filtering out dependencies due to `is_disjoint`
returning a false positive.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
Nice find

**Comment by BurntSushi** [comment]
It is absolutely wild to me that this bug fix has _zero_ impact on any of the resolutions in our tests. I feel like I should be slightly horrified by that.

**Review by ibraheemdev — APPROVED** [review]
Incredible catch. Also shocked that this managed to escape our testing, but because the `Edges::Boolean` node representation only applies to `extra` and `in` expressions.. that seems plausible.

**Comment by ibraheemdev** [comment]
I think the same issue is also present in `apply`. https://github.com/astral-sh/uv/blob/d3df97cc620110e9685e980ad9763390ebab1fc5/crates/uv-pep508/src/marker/algebra.rs#L863

**Comment by BurntSushi** [comment]
> but because the Edges::Boolean node representation only applies to extra and in expressions.. that seems plausible

Oooooooooooo. That makes more sense and makes me feel not-horrified about our tests hah. I naively assumed the boolean node was used for more stuff.

**Comment by BurntSushi** [comment]
> I think the same issue is also present in `apply`.
> 
> https://github.com/astral-sh/uv/blob/d3df97cc620110e9685e980ad9763390ebab1fc5/crates/uv-pep508/src/marker/algebra.rs#L863

Yeah nice catch. I fixed this too.

**Review by konstin — COMMENTED** [review]
Good catch!

**Pull request merged**
