### PR TITLE
Bump test timeout to 120s

### PR DESCRIPTION
**Pull request by zanieb**
90s is too low in our test suite :sob:

### CODE REVIEW

**Comment by ibraheemdev** [comment]
Even after https://github.com/astral-sh/uv/pull/3714?

**Comment by zanieb** [comment]
Yeah I saw it flake on `find_links_offline_match` at https://github.com/astral-sh/uv/actions/runs/9181553313/job/25248540367?pr=3677

**Comment by ibraheemdev** [comment]
That seems like a legitimate deadlock? Usually takes just over a second https://github.com/astral-sh/uv/actions/runs/9179591991/job/25242063661#step:8:753.

**Comment by zanieb** [comment]
_sigh_ I guess I'm bit by the deadlock haha

**Comment by zanieb** [comment]
Yeah I was just looking at that thinking it shouldn't be slow.

**Pull request closed without merging**
