### PR TITLE
Include exit code for build failures

### PR DESCRIPTION
**Pull request by konstin**
`uv pip install mysqlclient==2.1.1` on python 3.12 on windows, where the are no binary wheels:

grafik

Part of #2052.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'm finding it hard to tell which exit code belongs to which process, since `exit code: 2` appears twice and `exit code: 1` appears once. How does pip lay it out in this case?

**Comment by konstin** [comment]
Sharing linux now, windows after a reboot.

The linux comparison is asymmetric since we never call `egg_info`:

**pip**

image

**uv**

image

**Comment by konstin** [comment]
## Windows, my IDE terminal

### pip

It's cut off because that's my screen height.

grafik

### uv

grafik

## Default size windows terminal (powershell)

### pip

grafik

### uv

grafik

## Full height windows terminal (powershell)

This time a side-by-side view

grafik

**Comment by konstin** [comment]
I'm thinking about adding a message at the bottom after the stdout/stderr so it's immediately clear what failed even if setuptools and compilers spill so much output that it scrolled multiple pages.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
