### PR TITLE
Test cache against latest release in CI

### PR DESCRIPTION
**Pull request by zanieb**
Detect cache incompatibility issues like #2711 by testing against the last version of uv continuously

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
I think this is a decent sanity check. I wonder if it might be better to install something bigger like `homeassistant` to get a bigger sampling of packages.

This won't catch silent errors, but I think it will at least catch some subset of errors that `rkyv` validation doesn't catch.

**Comment by zanieb** [comment]
I'll test homeassistant and choose something prudent for test suite runtime

**Comment by BurntSushi** [comment]
Yeah, it looks like getting a broader sampling here matters. Things are hunky dory with `anyio`:

```
$ uv cache clean && rm -rf .venv
Clearing cache at: /home/andrew/.cache/uv
Removed 41594 files (246.2MiB)

$ uv-0.1.24 venv
Using Python 3.12.0 interpreter at: /home/andrew/.pyenv/versions/3.12.0/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

$ uv-0.1.24 pip install anyio
Resolved 3 packages in 80ms
Downloaded 3 packages in 23ms
Installed 3 packages in 5ms
 + anyio==4.3.0
 + idna==3.6
 + sniffio==1.3.1

$ uv-0.1.25 pip install anyio --reinstall-package anyio
Resolved 3 packages in 25ms
Installed 1 package in 6ms
 - anyio==4.3.0
 + anyio==4.3.0
```

But `homeassistant` lets me repro:

```
$ uv cache clean && rm -rf .venv
Clearing cache at: /home/andrew/.cache/uv
Removed 41598 files (246.2MiB)

$ uv-0.1.24 venv
Using Python 3.12.0 interpreter at: /home/andrew/.pyenv/versions/3.12.0/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

$ uv-0.1.24 pip install -q homeassistant

$ uv-0.1.25 pip install -q homeassistant --reinstall-package homeassistant
error: Failed to download and build: pyric==0.1.6.3
  Caused by: Failed to deserialize cache entry
  Caused by: expected version to start with a number, but no leading ASCII digits were found
```

**Review by BurntSushi — APPROVED** [review]
This LGTM.

**Pull request merged**
