### PR TITLE
If multiple indices contain the same version, use the first index

### PR DESCRIPTION
**Pull request by yorickvP**
This fixes resolving packages that publish an invalid stub to pypi, such as tensorrt-llm.

## Summary

In https://github.com/astral-sh/uv/pull/3138 , we implemented `unsafe-best-match`. However, it seems to not quite work as expected. When multiple indices contain the same version, it's not clear which index the current code uses. This PR fixes that to use the first index the package is in.

## Test Plan

```console
$ echo 'tensorrt-llm==0.11.0' | ./target/debug/uv pip compile - --extra-index-url https://pypi.nvidia.com --python-version=3.10 --index-strategy=unsafe-best-match --annotation-style=line
```

cc: @charliermarsh

### CODE REVIEW

**Comment by charliermarsh** [comment]
Yeah interesting, contrary to my expectation `kmerge` isn't "stable" by iterator:

```rust
#[cfg(test)]
mod tests {
    use itertools::Itertools;

    #[test]
    fn kmerge_reverse() {
        let a = vec![('a', 1), ('b', 2), ('c', 3)];
        let b = vec![('d', 1), ('e', 2), ('f', 3)];

        let its = [a, b];
        let its = its.iter().kmerge_by(|a, b| a.1 < b.1);

        let actual = its.collect::<Vec<_>>();
        let expected = vec![&('a', 1), &('d', 1), &('b', 2), &('e', 2), &('c', 3), &('f', 3)];

        assert_eq!(actual, expected);
    }
}
```

I didn't have any basis for expecting that so I don't think it's a bug, I just assumed it was true.

**Comment by charliermarsh** [comment]
@yorickvP - I tweaked to avoid re-comparing. Can you test that it's still passing on your test case?

**Comment by yorickvP** [comment]
Still works!

**Comment by charliermarsh** [comment]
Thanks!

**Pull request merged**
