### PR TITLE
Expose `toolchain-preference` as a CLI and configuration file option

### PR DESCRIPTION
**Pull request by zanieb**
Exposes the option added in #4416. Adds `--toolchain-preference` and `tool.uv.toolchain-preference` to configure if system or managed toolchains are preferred. Users can opt-out of managed toolchains or system toolchains entirely as well.

### CODE REVIEW

**Comment by zanieb** [comment]
Should we bikeshed the name? Should it just be `--toolchains`?

**Review by BurntSushi — APPROVED** [review]
LGTM.

As for the name... Is this something that you think will be commonly used on the CLI? If so, I think I'd favor a shorter name. Otherwise, I like the descriptiveness of `--toolchain-preference`.

One other possible downside is redundancy here. Namely, `--toolchain-preference prefer-system` has "prefer" twice in it, but arguably is just as clear if "prefer" only appeared once. Not quite sure what the right answer is there.

**Comment by zanieb** [comment]
> One other possible downside is redundancy here. Namely, --toolchain-preference prefer-system has "prefer" twice in it, but arguably is just as clear if "prefer" only appeared once.

Agree, this is a source of discomfort for me but idk it's also very clear.

I don't expect this to be used much from the CLI — mostly as a persistent configuration option.

**Comment by BurntSushi** [comment]
> I guess another option is I drop the `prefer` prefix so we'd have
> 
> `toolchain-preference = managed | system | only-managed | only-system | installed-managed`
> 
> which is pretty reasonable too?

I think that's probably okay. I thought of that too, but wondered whether it might leave folks wondering the difference between `managed` and `only-managed`.

**Pull request merged**
