### PR TITLE
build(uv-cli): Set correct gitdir and head path for worktree

### LINKED ISSUE #6196: `uv-cli` recompiles unnecessarily in worktree
Currently, when working in a worktree, `uv-cli` still recompiles even when there are no changes. Running `cargo check --verbose` multiple times shows something similar to the following::

``` shell-session
...
       Fresh backtrace v0.3.73
       Fresh uv-dispatch v0.0.1 (/Users/eth/workspace/astral-sh/uv-dev/crates/uv-dispatch)
       Fresh tikv-jemalloc-sys v0.6.0+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7
       Dirty uv-cli v0.0.1 (/Users/eth/workspace/astral-sh/uv-dev/crates/uv-cli): the file `.git/HEAD` is missing
   Compiling uv-cli v0.0.1 (/Users/eth/workspace/astral-sh/uv-dev/crates/uv-cli)
       Fresh nix v0.28.0
       Fresh clap_complete_command v0.6.1
       Fresh console v0.15.8
     Running `/Users/eth/workspace/astral-sh/uv-dev/target/debug/build/uv-cli-aeca9008583611ce/build-script-build`
       Fresh is_ci v1.2.0
       Fresh tikv-jemallocator v0.6.0
       Fresh ctrlc v3.4.4
...
```

This occurs because a worktree's `.git` is a file, not a directory, which means there is no `.git/HEAD` file for the worktree.

### PR DESCRIPTION
**Pull request by eth3lbert**
## Summary

Resolves #6196 .

## Test Plan

Run `cargo check` multiple times within the worktree and inspect the outputs. There should be no `Compiling` message after the first check.

### CODE REVIEW

**Comment by eth3lbert** [comment]
Some related info:
```
:)  tree /Users/eth/workspace/astral-sh -L 1
/Users/eth/workspace/astral-sh/
├── uv/
└── uv-dev/

(devshell) :)  git worktree list
/Users/eth/workspace/astral-sh/uv      20ef94b15 [main]
/Users/eth/workspace/astral-sh/uv-dev  3c313126b [uv-cli-worktree]
```

content of `.git` file in worktree:
```
(devshell) :)  /bin/cat /Users/eth/workspace/astral-sh/uv-dev/.git
gitdir: /Users/eth/workspace/astral-sh/uv/.git/worktrees/uv-dev
```
content of `HEAD` of worktree:
```
(devshell) :)  /bin/cat /Users/eth/workspace/astral-sh/uv/.git/worktrees/uv-dev/HEAD
ref: refs/heads/uv-cli-worktree
```

content of `commondir` of worktree:
```
(devshell) :)  /bin/cat /Users/eth/workspace/astral-sh/uv/.git/worktrees/uv-dev/commondir 
../..
```

**Comment by zanieb** [comment]
cc @charliermarsh can you actually review this since you use worktrees?

**Comment by charliermarsh** [comment]
Sure, no prob.

**Comment by eth3lbert** [comment]
> @eth3lbert I just merged #6825. I ended up submitting that before realizing this PR or #6196 existed. I merged that one over this one because I liked having the logic split out into a separate function. But this overall looked good too. Apologies for the duplicated effort and thank you for noticing this problem and submitting a fix. :-)

All good, thanks!

**Pull request closed without merging**
