### PR TITLE
Use `flask` in lieu of `black` for tool tests

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

On my machine, this reduces the test time from ~12 seconds to 4-5 seconds, since the package is so much smaller and the cold starts aren't as dramatic as `black`.

### CODE REVIEW

**Comment by zanieb** [comment]
Let's just create a project in `astral-test`? It should be trivial to publish a package with some entry points. I can do it this week.

**Comment by charliermarsh** [comment]
Ok, but I need this like... ASAP. The tests are so slow for me. I suppose I can do it now.

**Comment by zanieb** [comment]
I don't mind if you merge this in the meantime but it feels like a bit of a hack and I don't love the extra being included. 🤷‍♀️

**Comment by charliermarsh** [comment]
Can I change it to Flask in the meantime?

**Review by zanieb — APPROVED** [review]

**Pull request closed without merging**
