### PR TITLE
Combine `sys_platform` and `platform_system` in marker algebra

### LINKED ISSUE #7760: Incorporate knowledge of disjoint markers into simplification
There are some markers that we "know" cannot be true at the same time, despite the fact that it's not encoded in the grammar or schema at all.

For example, this is never true: `platform_system == 'Linux' and sys_platform == 'darwin'`.

If we encode knowledge about the markers that we "know" are disjoint, we can omit more forks, wheels, etc.

### LINKED ISSUE #9275: Ignore irrelevant platform-specific packages during resolution
Hi,

I've noticed that `uv`  still tries to resolve packages that are supposed to be irrelevant for the configured environment. I'm working on a server with a private registry where we don't have Darwin packages. When I try to install `ipykernel`, however, I see it still tries to resolve a Darwin-specific package, which then fails as it isn't available in our registry. Specifically, it's about `appnope`, which is configured as `'appnope>=0.1.2;platform_system=="Darwin"'` in ipykernel' s pyproject.toml.(https://github.com/ipython/ipykernel/blob/8c4901d691b1f309da3b80eefad5af13d7418185/pyproject.toml#L32C6-L32C13)

I'm using `uv` 0.5.2 on RHEL.

```toml
[project]
name = "test-project"
version = "0.1.0"
description = "My test project"
readme = "README.md"

dependencies = [
    "ipykernel ; sys_platform == 'linux'"
]

[tool.uv]
environments = [
    "sys_platform == 'linux'"
]
```  

```
$ uv lock -v 2>&1 | grep Darwin
DEBUG Solving split (python_full_version == '3.10'and platform_system == 'Darwin' and sys_platform == 'linux') ...
DEBUG Adding transitive dependency for ipykernel==x.x.x: appnope{platform_system == 'Darwin'}*
DEBUG Adding transitive dependency for ipykernel==x.x.x: appnope{platform_system == 'Darwin'}*
```

I think it might be related to https://github.com/astral-sh/uv/issues/9051#issuecomment-2470334438

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR adds a representation to the marker algebra to capture "known pairs" of `sys_platform` and `platform_system` values.

For example, we want to be able to detect that `sys_platform == 'win32'` and `platform_system == 'Darwin'` are disjoint.

There is some risk here, in that if there are platforms for which, e.g., `sys_platform == 'win32` but `platform_system` is not `Windows`, we'll get things wrong. I'm trying to weigh whether that's a real risk.

In theory, we could _maybe_ also include `os.name` here?

Closes #7760.
Closes #9275.

### CODE REVIEW

**Comment by Vinno97** [comment]
> In theory, we could maybe also include os.name here?

Yes. I was just about to comment on #9275  about this. 

For example, `jupyter-server` has a dependency on `pywinpty` for `os_name == 'nt'`. If want linux-only lock-file, a full dependency string would then have to be: `platform_system == 'Linux' and sys_platform == 'linux' and os_name == 'posix'`

**Comment by charliermarsh** [comment]
Yeah. I think it's a bit more challenging because there isn't a 1-to-1 mapping between `os.name` and `sys.platform` for Linux and macOS (they both use `posix`).

**Comment by charliermarsh** [comment]
(Not impossible but different than what I've encoded here.)

**Comment by Vinno97** [comment]
Since `os_name == 'posix'` could also be true for BSD and other more _esoteric_ POSIX operating systems, perhaps `os_name == ' posix'`  should entail `os_name != 'nt'`, with its subsequent `platform_system` and `sys_platform` restrictions?

**Comment by charliermarsh** [comment]
On reflection, what I have here is not correct. It fails this test (i.e., it thinks these are disjoint):

```rust
assert!(!is_disjoint(
    "sys_platform == 'cygwin'",
    "platform_system == 'Java'"
));
```

**Comment by charliermarsh** [comment]
Somewhat losing confidence here because it turns out Android also returns `"Linux"` for `platform_system`? Despite `sys_platform` returning `"android"`.

**Comment by Vinno97** [comment]
It seems like Poetry has gone though quite the rabbit hole for this themselves: https://github.com/python-poetry/poetry/issues/5192

But even after quite some pull requests, they closed the isue with this comment:
> Closing since there haven't been much improvements/fixes anymore in the last time and I can't come up with a good solution for merging sys_platform and platform_system.

(https://github.com/python-poetry/poetry/issues/5192#issuecomment-1229432876)

**Comment by charliermarsh** [comment]
I think it's absolutely possible to solve in our marker system, I just don't have the right solution here.

**Comment by konstin** [comment]
This is a tough one, my intuition is to encode know mismatch rather than known pairs. There's a tendency to subdivide platforms to accommodate new developments (the development of rust target triples is a good reference since it's more upstreamed than the python build vars), so i would encode tier 1 and tier 2 pairs that never match, such as darwin `sys_platform` and Windows in `platform_system`.

**Comment by Vinno97** [comment]
@konstin that's a good point and probably catches the majority of the standard cases with a smaller chance if breaking future cases

**Comment by charliermarsh** [comment]
Closing in favor of https://github.com/astral-sh/uv/pull/9444.

**Pull request closed without merging**
