### PR TITLE
Write relative paths with unnamed requirement syntax

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR falls back to writing an unnamed requirement if it appears to be a relative URL. pip is way more flexible when providing an unnamed requirement than when providing a PEP 508 requirement. For example, _only_ this works:

```
black @ file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable
```

Any other form will fail.

Meanwhile, _all_ of these work:

```
file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable
scripts/packages/black_editable
./scripts/packages/black_editable
file:./scripts/packages/black_editable
file:scripts/packages/black_editable
```

Closes https://github.com/astral-sh/uv/issues/3180.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
It makes me a little sad but yeah this is the pragmatic choice

**Comment by charliermarsh** [comment]
Me too.

**Comment by charliermarsh** [comment]
Windows failures... no...

**Comment by delfick** [comment]
hello, can a flag be introduced so that uv can output with the name?

When using the compiled .txt as a constraints file it can't find the name of the editable package when it has the `#egg=` in it (i.e. `-e file:some-package#egg=some-package` doesn't work with `error: Unnamed requirements are not allowed as constraints`) but if I change it to `some-package @ file:some-package` then it does work.

**Pull request merged**
