### PR TITLE
Expand environment variables in URLs

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR enables users to express relative dependencies via environment variables. Like pip, PDM, Hatch, Rye, and others, we now allow users to express dependencies like:

```text
flask @ file://${PROJECT_ROOT}/flask-3.0.0-py3-none-any.whl
```

In the compiled requirements file, we'll also preserve the unexpanded environment variable.

Closes https://github.com/astral-sh/puffin/issues/592.

### CODE REVIEW

**Comment by alelavelli** [comment]
How it is possible to dynamically read the local package content like in poetry with `my-local-package = { path = "local/package/path", develop = true }`? 

Because for now, the only solution I found is to recompile the pypropject.toml with `--refresh-package my-local-package`and then reinstall it

**Comment by charliermarsh** [comment]
@alelavelli -- Are you looking for `uv pip install -e ./local/package/path`?

**Comment by alelavelli** [comment]
Yes but directly from the pyproject.toml. Something like poetry:

[tool.poetry.dependencies]
my-local-package = {path = "../my-local-package", develop = true}

but with uv, like this:
[project]
dependencies = [
    "my-package @ file:/path/to/my/package" # with something to say -e
]

**Comment by charliermarsh** [comment]
Unfortunately I think it's not possible in `pyproject.toml`, because it's just not part of the standard PEP 508 specification.

**Comment by fruch** [comment]
> Unfortunately I think it's not possible in `pyproject.toml`, because it's just not part of the standard PEP 508 specification.

just an update for whom running into it, `uv add` now supports it

```
uv add --editable ./local-path/
```

which maps to `pyproject.toml`
```
[tool.uv.sources]
my_package = { path = "local-path", editable = true }
```

**Pull request merged**
