### PR TITLE
Add prerelease compatibility check

### LINKED ISSUE #7977: uv python install does not respect rc qualifiers
It installs rc2 even though I request rc3... 😊 

```bash
❯ uv python install 3.13.0rc3 --native-tls -vv
    0.000272s DEBUG uv uv 0.4.17
    0.000755s DEBUG uv_fs Acquired lock for `/Users/bgabor8/Library/Application Support/uv/python`
Searching for Python versions matching: Python 3.13rc3
    0.001142s DEBUG uv_client::base_client Using request timeout of 30s
 uv_python::downloads::fetch self=ManagedPythonDownload { key: PythonInstallationKey { implementation: Known(CPython), major: 3, minor: 13, patch: 0, prerelease: "rc2", os: Os(Darwin), arch: Arch(Aarch64(Aarch64)), libc: None }, url: "https://github.com/indygreg/python-build-standalone/releases/download/20240909/cpython-3.13.0rc2%2B20240909-aarch64-apple-darwin-install_only_stripped.tar.gz", sha256: Some("9e17f9fcc314a5dd489089a7502a525c4dd08af862f9cf33b52161a752f2a5b7") }, download=cpython-3.13.0rc2-macos-aarch64-none
   11.971556s  11s  DEBUG uv_python::downloads Downloading https://github.com/indygreg/python-build-standalone/releases/download/20240909/cpython-3.13.0rc2%2B20240909-aarch64-apple-darwin-install_only_stripped.tar.gz to temporary location: /Users/bgabor8/Library/Application Support/uv/python/.cache/.tmphDfaX1
   11.971687s  11s  DEBUG uv_python::downloads Extracting cpython-3.13.0rc2%2B20240909-aarch64-apple-darwin-install_only_stripped.tar.gz
   12.968445s  12s  DEBUG uv_python::downloads Moving /Users/bgabor8/Library/Application Support/uv/python/.cache/.tmphDfaX1/python to /Users/bgabor8/Library/Application Support/uv/python/cpython-3.13.0rc2-macos-aarch64-none
Installed Python 3.13.0rc2 in 12.96s
 + cpython-3.13.0rc2-macos-aarch64-none
   12.969182s DEBUG uv_fs Released lock at `/Users/x/Library/Application Support/uv/python/.lock`
```

```
❯ uv --version
uv 0.4.17 (d2e7b40ce 2024-09-27)
```

### PR DESCRIPTION
**Pull request by trag1c**
## Summary

Closes #7977. Makes `PythonDownloadRequest` account for the prerelease part if allowed. Also stores the prerelease in `PythonInstallationKey` directly as a `Prerelease` rather than a string.

## Test Plan

Correctly picks the relevant prerelease (rather than picking the most recent one):
```
λ cargo run python install 3.13.0rc2
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/uv python install 3.13.0rc2`
Searching for Python versions matching: Python 3.13rc2
cpython-3.13.0rc2-macos-aarch64-none ------------------------------ 457.81 KiB/14.73 MiB                                                                                                                    ^C

λ cargo run python install 3.13.0rc3                 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/uv python install 3.13.0rc3`
Searching for Python versions matching: Python 3.13rc3
Found existing installation for Python 3.13rc3: cpython-3.13.0rc3-macos-aarch64-none
```

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
Well done!

**Comment by zanieb** [comment]
Looks like it will need an update following #8010

**Comment by trag1c** [comment]
Looks like GitHub didn't agree with me on the conflict resolution 😄

**Review by gaborbernat — COMMENTED** [review]
No tests here? 🤔

**Comment by zanieb** [comment]
Feel free to add some!

**Pull request merged**
