### PR TITLE
Respect `requires-python` when prefetching

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This is fallout from https://github.com/astral-sh/uv/pull/4705. We need to respect `requires-python` in the prefetch code to avoid building unsupported distributions.

Closes https://github.com/astral-sh/uv/issues/4898.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Will add test coverage.

**Review by BurntSushi — APPROVED** [review]

**Comment by zanieb** [comment]
As a side-note, are we tracking not hard-failing on errors during pre-fetch? Seems wild that this can crash the resolution.

**Comment by charliermarsh** [comment]
@zanieb - I don't think so... Part of the problem is that we _do_ need to track failures here, we can't just skip silently, since if we later request the package and it fails in a way that we consider a hard failure (like a build failure), that does need to be surfaced.

**Comment by charliermarsh** [comment]
I created https://github.com/astral-sh/uv/issues/4901.

**Pull request merged**
