### PR TITLE
Bump version to 0.2.27

### PR DESCRIPTION
**Pull request by zanieb**

### CODE REVIEW

**Comment by notatallshaw** [comment]
I was surprised to see a Friday release, as I'd noticed they aren't as common. Last one was on 2024-05-24, statistics of releases per day of the week (as measured in Americas/New_York):

```
15  Monday
15  Tuesday
18  Wednesday
13  Thursday
 6  Friday
 3  Saturday
 4  Sunday
```

\</useless-trivia>

**Comment by zanieb** [comment]
We vaguely try to avoid it to reduce weekend churn but I didn't even think about it today :)

**Comment by charliermarsh** [comment]
@notatallshaw - You are impressively attuned to the project!

**Comment by zanieb** [comment]
Needed #5233 to fix Windows builds and I added #5232.

**Pull request merged**
