### PR TITLE
Include Git member information when getting metadata from cache

### LINKED ISSUE #8887: uv add workspace fails misteriously from git but not locally
I tried to add as a dependency to a project a workspace that is found on git by doing

```python
uv init
uv add git+https://github.com/NeuralQXLab/omnia  --no-sync
```

this fails with the error
```bash
❯ uv add git+https://github.com/NeuralQXLab/omnia  --no-sync
 Updated https://github.com/NeuralQXLab/omnia (5d97a5b)
error: Requirements contain conflicting URLs for package `netket` in split `python_full_version == '3.12.*'`:
- file:///Users/filippo.vicentini/.cache/uv/git-v0/checkouts/75e22c3618b1966a/5d97a5b/external/netket
- file:///Users/filippo.vicentini/.cache/uv/git-v0/checkouts/75e22c3618b1966a/5d97a5b/external/netket
```

Instead, if I do the same but from a cloned version of the workspace, it just works

```python
uv init
git clone https://github.com/NeuralQXLab/omnia
uv add ./omnia
```

While the workspace is private, the structure is something that looks like
```
# omnia/pyproject.toml
[project]
name = "omnia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "netket",
    "netket_pro",
    "netket_checkpoint",
    "deepnets",
]

[tool.uv]
dev-dependencies = [
    "networkx>=3.4.2",
    "pytest-xdist>=3.6.1",
    "pytest>=8.3.3",
]

[tool.uv.sources]
netket = { workspace = true }
netket_pro = { workspace = true }
netket_checkpoint = { workspace = true }
deepnets = { workspace = true }

[tool.uv.workspace]
members = ["packages/*", "utils/*", "external/netket"]
exclude = ["utils/jax-rocm-autoinstall"]
```

However the error is not very telling, and I do not understand what I can do to fix it.

### PR DESCRIPTION
**Pull request by ericmarkmartin**
## Summary

Include the `git_member` when fetching metadata from cache.

h/t to @PhilipVinc for the suggested fix

Resolves #8887 

## Test Plan

Pending

### CODE REVIEW

**Comment by ericmarkmartin** [comment]
It looks like some of the failing tests are the "too many requests" thing I was alluded to in [my comment](https://github.com/astral-sh/uv/issues/8887#issuecomment-2495273694) on the issue

**Comment by charliermarsh** [comment]
Yeah I think something is up with that index. I should look into removing our dependency on it.

**Review by charliermarsh — APPROVED** [review]
This seems right, but is there a way to test it?

**Comment by ericmarkmartin** [comment]
> This seems right, but is there a way to test it?

Could we set up a packse like the example given in the issue (see https://github.com/PhilipVinc/uvtest/tree/dab673b4ad5c6f1335c491baf49ad4965562e876)?

Also, I generally am pretty clueless about uv's testing story (I know it's snapshot based, but that's about it) but would be eager to learn by writing some tests here

**Comment by zanieb** [comment]
If it would help we could add a repository in our test org, e.g. https://github.com/astral-test/uv-submodule-pypackage

I'm not sure I understand the issue here though.

**Comment by ericmarkmartin** [comment]
> If it would help we could add a repository in our test org, e.g. https://github.com/astral-test/uv-submodule-pypackage

That could be helpful. I take it that'd be easier than getting packse to serve git repos? One maybe relevant question here is whether we can use `git+` with file-scheme urls?

**Comment by zanieb** [comment]
>  I take it that'd be easier than getting packse to serve git repos?

Yeah this would probably be a pain.

> One maybe relevant question here is whether we can use git+ with file-scheme urls?

I don't quite follow, perhaps you should tell me what a test case would look like given a `uv` binary and I can help construct it? Perhaps as an answer to your question, a test could just clone a repository to a temporary directory then pass that path to uv?

**Comment by ericmarkmartin** [comment]
> Perhaps as an answer to your question, a test could just clone a repository to a temporary directory then pass that path to uv?

For sure, I just wasn't at my computer earlier. I just confirmed that this works, though unfortunately testing this with @PhilpVinc's test repository (see linked issue) had the conflicting URL issue reoccur 😞

**Comment by konstin** [comment]
If you need inspiration for tests, there are `transitive_dep_in_git_workspace_no_root` and `transitive_dep_in_git_workspace_with_root` from previous bug fixes in the area

**Comment by charliermarsh** [comment]
I'd like to get this merged today so we can release it. I'll add a test if needed.

**Comment by ericmarkmartin** [comment]
Hey,Apologies for not getting to this, I had to get ready for a vacation. I’m out of the country without my personal computer right now so I think the chances I can do this today are pretty low.On Dec 2, 2024, at 14:10, Charlie Marsh ***@***.***> wrote:﻿
I'd like to get this merged today so we can release it. I'll add a test if needed.

**Comment by charliermarsh** [comment]
@ericmarkmartin -- No problem at all!

**Pull request merged**
