### PR TITLE
Use a cross-platform representation for relative paths in `pip compile`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

I haven't tested on Windows yet, but the idea here is that we should use a portable representation when printing paths.

I decided to limit the scope here to paths that we write to output files.

Closes https://github.com/astral-sh/uv/issues/3800.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]
Cool if it works!

**Comment by charliermarsh** [comment]
Famous last words.

**Comment by charliermarsh** [comment]
Alright, this isn't quite what we want. But I think I _can_ use this crate to solve this specific problem.

**Comment by charliermarsh** [comment]
Specifically, I think I can use this when we `.join`.

**Comment by charliermarsh** [comment]
Ok, this definitely is not doing what I want.

**Comment by charliermarsh** [comment]
Okay, this actually _does_ do what we want.

**Pull request merged**
