### PR TITLE
Cache metadata for source tree dependencies

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR re-introduces caching for source trees. In short, we treat the metadata as cached unless the `pyproject.toml`, `setup.py`, or `setup.cfg` file changes. This is a heuristic and not a good one, especially for extension modules, but without it, we have to rebuild every project every time (unless you have static metadata, like a `pyproject.toml` that we can read directly).

Now that we support persistent configuration, users should add:

```toml
[tool.uv]
reinstall = ["foo"]
```

If they want a package to always be refreshed (ignore cache) and reinstalled (ignore environment).

Closes https://github.com/astral-sh/uv/issues/5420.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Should `refresh` imply `reinstall`? I hate that you need to specify both, it's really bad. But they mean different things. `reinstall` tells us to ignore the already-installed version, and `refresh` tells us to ignore the already-cached metadata.

**Comment by charliermarsh** [comment]
(I expect a couple tests to fail.)

**Comment by charliermarsh** [comment]
I guess it would make more sense for `reinstall` to imply `refresh`.

**Comment by charliermarsh** [comment]
This is only "breaking" in the sense that some things that weren't cached are now cached, so some users that rely on it may see a change in behavior. They will not see any errors.

**Comment by zanieb** [comment]
I wonder if we need another label for that kind of thing? Otherwise we're automatically bumping to the next minor version because of the breaking label (which is nice for flagging things, but annoying to change as a release manager. Alternatively, I can document how to bypass the automatic bump in Rooster?

**Comment by charliermarsh** [comment]
I relabeled it though not sure what the best options are.

**Review by konstin — APPROVED** [review]

**Pull request merged**
