### PR TITLE
Pin publish test to 3.12

### PR DESCRIPTION
**Pull request by konstin**
The bump to 3.13 broke the test

### CODE REVIEW

**Comment by ranjithrajv** [comment]
How about introducing a command or flag to uv publish that allows setting a custom timeout value? 
This would offer greater flexibility by letting users specify the timeout according to their specific requirements instead of relying on a default fixed value.

**Comment by konstin** [comment]
This is applicable to the test script only

**Comment by zanieb** [comment]
Oof 20 minutes is really long for the test to run. Why is it taking so long?

**Comment by zanieb** [comment]
And it still failed here — I think there needs to be a different solution.

**Pull request merged**
