### PR TITLE
Add support for remaining pip-supported file extensions

### LINKED ISSUE #7365: Add support for remaining file extension aliases
See: https://github.com/pypa/pip/blob/111eed14b6e9fba7c78a5ec2b7594812d17b5d2b/src/pip/_internal/utils/filetypes.py#L8.

It's an identical change to #7201, but with a different set of aliases. Good first PR for anyone interested.

### PR DESCRIPTION
**Pull request by Aditya-PS-05**
closes #7365 

Summary

This pull request adds support for additional file extension aliases in the SourceDistExtension and ExtensionError enums. The newly supported file extensions include .tbz, .tgz, .txz, .tar.lz, .tar.lzma. These changes align the extensions supported by the SourceDistExtension with those used in Python packaging tools, enhancing compatibility with a broader range of source distribution formats.

Test Plan
should be added or updated to verify that the new extensions are correctly recognized as valid source distributions and that errors are correctly raised when unsupported extensions are provided.

### CODE REVIEW

**Comment by Aditya-PS-05** [comment]
I have updated some test cases which were initially for old extensions and as I have updated the extensions. I have updated these tests to work for new extensions also.
Thank you.

**Comment by charliermarsh** [comment]
For future reference:

```
gzip -cd Flask-2.0.0.tar.gz | lzma > Flask-2.0.0.tar.lzma
gzip -cd Flask-2.0.0.tar.gz | xz > Flask-2.0.0.tar.xz
```

**Comment by charliermarsh** [comment]
Or, to create `.tar` from `.tar.gz`: `gzip -d Flask-2.0.0.tar.gz`

**Comment by Aditya-PS-05** [comment]
> For future reference:
> 
> ```
> gzip -cd Flask-2.0.0.tar.gz | lzma > Flask-2.0.0.tar.lzma
> gzip -cd Flask-2.0.0.tar.gz | xz > Flask-2.0.0.tar.xz
> ```

I will try.

**Pull request merged**
