### PR TITLE
Attempt to install PyTorch on CI

### PR DESCRIPTION
**Pull request by charliermarsh**
Trying to reproduce reported errors.

### CODE REVIEW

**Comment by charliermarsh** [comment]
@konstin - did you do anything special to reproduce this?

**Comment by janosh** [comment]
maybe try with a different Python version (e.g. 3.9) and into `--system` Python and with cache.

at least that's the setup we have over at https://github.com/materialsproject/pymatgen and we used to get time outs until [this workaround](https://github.com/materialsproject/pymatgen/commit/0ab8707aa1ef5db1341d1c0429962fff3c560d19#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R105)

**Comment by konstin** [comment]
I only had them on CI, e.g. https://github.com/konstin/vws-python-mock/actions/runs/8081842244/job/22081322082 . They are still rare, even on CI with 50 jobs it often passes.

**Comment by adamtheturtle** [comment]
> I only had them on CI, e.g. https://github.com/konstin/vws-python-mock/actions/runs/8081842244/job/22081322082 . They are still rare, even on CI with 50 jobs it often passes.

Thank you @konstin for looking into this.
I run a few hundred jobs per day and I hit this on average more than once per day, often in clusters (e.g. this run https://github.com/VWS-Python/vws-python-mock/actions/runs/8340991068 has 79 jobs with 24 failures).

**Pull request closed without merging**
