### PR TITLE
Support `uv run -m foo` to run a module

### LINKED ISSUE #6638: How to run a library module?
What is the recommended way for running a library module like I would do in vanilla python with the `-m` flag.

E.g.
```sh
python -m mylibrary.module
```

### PR DESCRIPTION
**Pull request by j178**
## Summary

This is another attempt using `module: bool` instead of `module: Option<String>` following #7322. 
The original PR can't be reopened after a force-push to the branch, I've created this new PR.

Resolves #6638

### CODE REVIEW

**Comment by bluss** [comment]
Here's a tricky test case: does the equivalent of `uv run python -m pdb -m tarfile` work?  pdb is an example of a module that accepts `-m` in its own command (to launch debugging for a module..)

**Comment by j178** [comment]
`uv run -m pdb -m tarfile` does work:
```console
$ cargo run -- run -m pdb -m tarfile
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.38s
     Running `target\debug\uv.exe run -m pdb -m tarfile`
> c:\users\nigel\appdata\roaming\uv\data\python\cpython-3.12.1-windows-x86_64-none\lib\tarfile.py(29)<module>()
-> """Read from and write to tar format archives.
```

**Review by zanieb — APPROVED** [review]
Thanks!

**Comment by a-reich** [comment]
I came to this repo to ask for adding a shortcut to `uv run python -m`, and to my delight found this was already merged 😃 wonderful job!

**Comment by bluss** [comment]
I guess that it allows reordering -m, anywhere before the module name, but maybe that doesn't matter (?)

**Pull request merged**
