### PR TITLE
Use logo in documentation

### PR DESCRIPTION
**Pull request by zanieb**
Before
Screenshot 2024-07-24 at 3 12 28 PM

After
Screenshot 2024-07-24 at 3 11 07 PM

Alternatively
Screenshot 2024-07-24 at 3 10 45 PM

### CODE REVIEW

**Comment by zanieb** [comment]
Honestly not in love with the look, seems like it'd need a tweak to the size.

**Review by charliermarsh — APPROVED** [review]
Yeah I prefer uv logo to Astral logo. Would be nice to add more Astral to the footer if possible but not sure.

**Comment by zanieb** [comment]
Think I should shrink it a little as in the later comment?

**Comment by charliermarsh** [comment]
I slightly prefer the larger version but I'm fine with either.

**Comment by zanieb** [comment]
Note we use the lightning bolt logo in Ruff (which looks pretty nice).

**Pull request merged**
