### PR TITLE
Remove trailing period from user-facing messages

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Per #5209, we only show periods in messages when the message itself spans more than a single sentence.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Do people like this?

**Comment by zanieb** [comment]
I like consistency. I'm not sure I have a strong preference here yet, I'm curious to see if it feels different?

**Comment by zanieb** [comment]
The preview warnings sure stuck out before though

**Comment by charliermarsh** [comment]
Alright let's roll with it.

**Comment by charliermarsh** [comment]
Updating the test fixtures now which is a bit of a pain :)

**Pull request merged**
