### PR TITLE
Turn off text wrapping in non-scenario fixtures

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We do this in the scenarios, but weren't setting it elsewhere.

### CODE REVIEW

**Comment by zanieb** [comment]
FWIW I was considering turning this back on in scenarios now that the names are shorter? I'm not sure if it helps or hurts generally.

**Comment by charliermarsh** [comment]
I don't feel strongly. Defer to you.

**Comment by zanieb** [comment]
Let's just go with consistency for now and we can consider it later.

**Comment by charliermarsh** [comment]
Kk I'll fix the failures.

**Pull request merged**
