### PR TITLE
Fix keyring auth

### PR DESCRIPTION
**Pull request by emarsden-iso**

### CODE REVIEW

**Comment by zanieb** [comment]
Hi! Is this a duplicate of the fix in #3206?

**Comment by emarsden-iso** [comment]
> Hi! Is this a duplicate of the fix in #3206?

Oh dear, I think so :)

Let me check your fix fixes my issue, then I guess can close this?

**Comment by emarsden-iso** [comment]
> > Hi! Is this a duplicate of the fix in #3206?
> 
> Oh dear, I think so :)
> 
> Let me check your fix fixes my issue, then I guess can close this?

Confirmed keyring authentication is working at HEAD, can close. I'll try to remember those wasted 2 hours fondly

**Comment by zanieb** [comment]
Thanks for hopping on it regardless :) feel free to review that one and let me know if you think more should change.

**Pull request closed without merging**
