### PR TITLE
Move maturin test coverage into CI

### PR DESCRIPTION
**Pull request by zanieb**
This test can take over 60s to run, which is too much for a unit test. We'll run it in a separate CI job to retain coverage.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Can we just remove this entirely? Seems like a lot of complexity to have an maintain job just for this.

**Comment by zanieb** [comment]
I don't feel strongly, we could remove it. Why did @konstin think coverage was important?

**Comment by zanieb** [comment]
My goal here is immediately unblock the rest of my PRs which are failing due to this test. It's trivial to remove after this merges so I have a preference to merge this as-is and consider dropping coverage separately.

**Comment by charliermarsh** [comment]
Ok, feel free to merge, I'll remove in a separate PR then. Bias towards action :)

**Pull request merged**
