### PR TITLE
Make `--directory` a global argument

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Cargo makes this global (and uses the same technique). It's still hidden so we can always decide to remove it.

### CODE REVIEW

**Comment by bluss** [comment]
Changing directory is a different thing and makes uv run harder to use like that (if you pass relative paths to an uv run command, it might not work so well.)

**Comment by charliermarsh** [comment]
What's harder about it? Why is it wrong to resolve paths relative to the provided directory?

**Comment by charliermarsh** [comment]
(I mean, it's easy to change -- we just track a current directory globally in `uv-fs`, add a setter, and always read from there rather than using `CWD`.)

**Comment by bluss** [comment]
I'm thinking that you have something like

```bash
$ uv --directory path/to/proj run the_command --flag ./myfile.txt
# <------- uv run part ---------> <-- regular command part  ---->
```

Ideally the uv run part should just be transparent. It brings forth the environment in where the program executes. The regular command line part of the command shouldn't have to change.

**Comment by charliermarsh** [comment]
That makes sense. I can change it up.

**Pull request merged**
