### PR TITLE
Add `uv tree --outdated`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Similar to `pip list --outdated`, but for `uv tree`.

## Test Plan

Looks like:

```
foo v0.1.0
└── flask v2.0.0 (latest: v3.0.3)
    ├── click v8.1.7
    ├── itsdangerous v2.2.0
    ├── jinja2 v3.1.4
    │   └── markupsafe v3.0.2
    └── werkzeug v3.1.2
        └── markupsafe v3.0.2
```

With `(latest: v3.0.3)` in bold cyan.

### CODE REVIEW

**Comment by zanieb** [comment]
I presume you'll add a test :)

**Comment by charliermarsh** [comment]
Do you think we should _only_ show outdated packages?

**Comment by zanieb** [comment]
Probably? I guess I'd be surprised to see packages that aren't outdated, but we need to anyway to display the tree?

**Comment by charliermarsh** [comment]
We could basically limit the tree to outdated packages.

**Comment by charliermarsh** [comment]
But it would often be just a list of packages since they may not be connected.

**Comment by zanieb** [comment]
Let's just start with showing everything. Maybe bold the outdated ones?

**Comment by zanieb** [comment]
I see it's already bold

**Comment by charliermarsh** [comment]
Yeah it's bold and blue.

**Review by zanieb — APPROVED** [review]

**Pull request merged**
