### PR TITLE
Rename `uv sync --no-clean` to `uv sync --inexact`

### PR DESCRIPTION
**Pull request by zanieb**

### CODE REVIEW

**Comment by zanieb** [comment]
I'm not convinced that we shouldn't perform an exact sync by default, and while I like the `--exact` / `--no-exact` names — I don't feel that we should adjust the default behavior because it's easier to write the names of the flag. 

I worry `--no-exact` is not obvious enough on its own.

**Comment by zanieb** [comment]
(I don't love this name either, but it cannot remain `--no-clean` due to the conflict with cache clean semantics)

**Comment by zanieb** [comment]
- `--no-prune`
- `--retain`
- `--preserve-extras` (conflicts with the optional deps concept)
- `--preserve`
- `--keep-unused`
- `--skip-prune`

**Comment by notatallshaw-gts** [comment]
`--no-remove`
`--no-delete` (taken from rsync `delete` terminology)

**Comment by zanieb** [comment]
But we _will_ remove packages if they conflict with the requirements of the project.

**Comment by charliermarsh** [comment]
`--ignore-unused`? `--skip-unused`?

**Comment by zanieb** [comment]
I worry a little about "unused" since they could be used just not declared.

**Comment by zanieb** [comment]
Opting for `--inexact` with a `--no-exact` alias.

**Review by charliermarsh — APPROVED** [review]

**Pull request merged**
